### ISSUE TITLE
Can't export a C2 cordova project with C3 export manager

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#1407]
## Problem description

I'm clicking the + sign on the export manager in C3 and adding my exported Cordova project from C2 which I exported following the exact instructions in the guide by Ashley. 

Everything is shown correctly, the project name, size 250mb, everything good. But when I click "build application" it immediately crashes with the crash report pasted here.

## Observed result

C3 crashes when trying to export a C2 cordova project zip

## Expected result

Export the C2 cordova project correctly

## Affected browsers

* Chrome: yes

## System details

Error report information
Type: unhandled rejection
Reason: Error: Failed to execute 'setAttribute' on 'Element': 2 arguments required, but only 1 present. @ TypeError: Failed to execute 'setAttribute' on 'Element': 2 arguments required, but only 1 present. at ǃr.ǃo.ǃsZ.ǃvis.ǃviy (https://editor.construct.net/r89/main.js:155:19035) at ǃr.ǃo.ǃsZ.ǃvis.ǃviC (https://editor.construct.net/r89/main.js:155:16923) at app.ǃuT.then (https://editor.construct.net/r89/main.js:155:22729)
Stack: TypeError: Failed to execute 'setAttribute' on 'Element': 2 arguments required, but only 1 present. at ǃr.ǃo.ǃsZ.ǃvis.ǃviy (https://editor.construct.net/r89/main.js:155:19035) at ǃr.ǃo.ǃsZ.ǃvis.ǃviC (https://editor.construct.net/r89/main.js:155:16923) at app.ǃuT.then (https://editor.construct.net/r89/main.js:155:22729)
Construct 3 version: r89
URL: https://editor.construct.net/
Date: Wed Mar 21 2018 13:23:48 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 17.8 s

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by damjancd** [comment]
My bad, had an older non-BETA version of C3 on my desktop
