### ISSUE TITLE
GooglePlay fail Signin on Android

### ISSUE THREAD

**Issue by luisforte** [Scirra/Construct-3-bugs#1430]
## Problem description

Play Games Plugin compiled on Android Studio fail on Signin action with SigninConfigurationError

First time open APP Play Games Sigin with Config error, close app and open again to app CRASH

My SHA-1 certificate is right, my API Console right configured, i use Google Sigin and maked my Oath2 with right sha-1 certificate provid by Google Console.

## Attach a .c3p

*Any Android Project with Play Games Plugin*

## Steps to reproduce

Add PlayGames plugin to project
Compile Project
Submit on PlayStore
Open and try to Signin with Play Games

## Observed result

First time Play Games Apparently Signin normal, but behind to logcat you see a SignInConfiguration error... and nothing is retrive with GetPlayerDetails. If you close the APP after first Signin next time you open the APP CRASH! with same error in Logcat "internal.SignInConfiguration"

## Expected result

Play Games Signin and retreiv players Score, send score etc.

## Affected browsers

* Chrome: yes/
* Firefox: yes/
* Edge: yes/
* Safari: yes/

Tested on Samsung J7
<details><summary>LOGCAR of Error</summary>

 E/Parcel: Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
                                         java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:324)
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
                                             at android.os.Parcel.readParcelable(Parcel.java:2358)
                                             at android.os.Parcel.readValue(Parcel.java:2264)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                             at android.os.BaseBundle.getString(BaseBundle.java:920)
                                             at android.content.Intent.getStringExtra(Intent.java:6221)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2751)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2209)
                                             at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6592)
                                             at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6347)
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170)
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4167)
                                             at android.os.Binder.execTransact(Binder.java:453)
                                          Caused by: java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                             at java.lang.Class.classForName(Native Method) 
                                             at java.lang.Class.forName(Class.java:324) 
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2404) 
                                             at android.os.Parcel.readParcelable(Parcel.java:2358) 
                                             at android.os.Parcel.readValue(Parcel.java:2264) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2614) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                             at android.os.BaseBundle.getString(BaseBundle.java:920) 
                                             at android.content.Intent.getStringExtra(Intent.java:6221) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2751) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2209) 
                                             at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6592) 
                                             at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6347) 
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170) 
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4167) 
                                             at android.os.Binder.execTransact(Binder.java:453) 
                                          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

</details>

**Comment by luisforte** [comment]
For more information
A PrintScreen of LogCat when any action (Get Player Details for example) if maked, after first re-open APP Crash (App stoped working)

![image](https://user-images.githubusercontent.com/20118021/37924962-c42c5946-3109-11e8-9aef-d37221f0c113.png)

**Comment by luisforte** [comment]
Update: Due Android Studio and Cordova Update
First time i Open the app and Signin the "Send Player Score" works, but i still cant retrieve any Data.
Still crashing after app re-open with same error in logcat.

**Comment by shortercode** [comment]
The first stack trace is apparently a samsung oddity, but it shouldn't actually cause any issues. Was there another error in the console which was labelled as fatal that could have caused the crash? I'm trying to repeat that one anyway, but need to wait for our S8 to recharge a bit first.

The second trace is a little weird. By the looks of it the activity is signed in, and has a player client assigned to it but the plugin was never notified of the sign in. Hopefully just an edge case in sign in restoration but could be something more painful.
