### ISSUE TITLE
Crash on creating new projects after closing existing project

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#1491]
## Problem description

This is an odd one that I realised recently. I have no idea why this happens. What I did was open one of my existing projects, close it and creating a new project.

## Steps to reproduce

I believe this might be a specific issue to my project file only. I hope it will be possible for the bug to be fixed without me having to share my project.

## Observed result

When the crash happens, I see the most recent layout view of the closed project in the background.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r95/main.js, line 63, col 8477
Message: Uncaught TypeError: Cannot read property 'useProgram' of null
Stack: TypeError: Cannot read property 'useProgram' of null at ǃt.ǃdu.ǃtdg.ǃtZy (https://editor.construct.net/r95/main.js:63:8477) at ǃt.ǃdu.ǃrFq.ǃyR (https://editor.construct.net/r95/main.js:63:36609) at window.ǃrbX.ǃzN (https://editor.construct.net/r95/components/editors/layoutView/layoutView.js:1:45144) at window.ǃbW.ǃrbC (https://editor.construct.net/r95/components/editors/layoutView/layoutView.js:1:6873) at ǃrb$ (https://editor.construct.net/r95/components/editors/layoutView/layoutView.js:1:1834)
Construct 3 version: r95
URL: https://editor.construct.net/r95/
Date: Mon Apr 16 2018 23:33:46 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 317 s

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r95 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by jaydonteh** [comment]
> System

**Comment by AshleyScirra** [comment]
I think I could figure this out from the crash report, but I can't verify it without steps to reproduce. Let's check at the next release and see if the problem is resolved.

**Comment by AshleyScirra** [comment]
Can you test r95.2 and see if the issue is resolved there?

**Comment by jaydonteh** [comment]
Fixed!
