### ISSUE TITLE
Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project

### ISSUE THREAD

**Issue by saltandpixel** [Scirra/Construct-3-bugs#1495]
## Problem description

Project will not open

## Attach a .c3p

https://drive.google.com/open?id=12AX_VVldGh3NIq-wBSUW7mZq-LA1smlx

## Steps to reproduce

1. launch c3
2. select game from cloud
3.

## Observed result

loads but doesn't open

## Expected result

Open build

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: invalid parameter id 'color-(red)' @ Error: invalid parameter id 'color-(red)' at e.ǃwG (https://editor.construct.net/r95/main.js:63:160177) at e.ǃnv (https://editor.construct.net/r95/main.js:63:161983) at i.ǃnv (https://editor.construct.net/r95/main.js:63:241681) at o.ǃqri (https://editor.construct.net/r95/main.js:63:281949) at d.ǃqrB (https://editor.construct.net/r95/main.js:63:266199) at Object.ǃt.ǃA [as ǃrzv] (https://editor.construct.net/r95/main.js:63:265356) at n (https://editor.construct.net/r95/main.js:2:198792) at t (https://editor.construct.net/r95/main.js:2:198578)
Stack: Error: invalid parameter id 'color-(red)' at e.ǃwG (https://editor.construct.net/r95/main.js:63:160177) at e.ǃnv (https://editor.construct.net/r95/main.js:63:161983) at i.ǃnv (https://editor.construct.net/r95/main.js:63:241681) at o.ǃqri (https://editor.construct.net/r95/main.js:63:281949) at d.ǃqrB (https://editor.construct.net/r95/main.js:63:266199) at Object.ǃt.ǃA [as ǃrzv] (https://editor.construct.net/r95/main.js:63:265356) at n (https://editor.construct.net/r95/main.js:2:198792) at t (https://editor.construct.net/r95/main.js:2:198578)
Construct 3 version: r95
URL: https://editor.construct.net/r95/
Date: Mon Apr 16 2018 20:45:48 GMT-0400 (EDT)
Uptime: 187.6 s

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.10_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r95 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by saltandpixel** [comment]
This happened with last update too - I would really appreciate recovering this file this time. I seriously don't have it in me to remake this game, again.

**Comment by saltandpixel** [comment]
[add ons.zip](https://github.com/Scirra/Construct-3-bugs/files/1919931/add.ons.zip)

**Comment by shortercode** [comment]
Have you updated normalmap extended recently? It says the file was saved with 1.0.0.0 but the version you sent was 1.1.0.0 the reason I say is because it looks like the parameter names have changed, which is why it isn't loading.

**Comment by saltandpixel** [comment]
I had to reset my browser recently which makes me reinstall the add ons -
maybe I installed the wrong plugin. Can I try it and get back to you?

**Comment by saltandpixel** [comment]
That's what it was. I installed the wrong normalmap addon. It's working now.

**Comment by saltandpixel** [comment]
Thank you for your help - I was freaking out!

**Comment by shortercode** [comment]
That's okay. Do you want me to send you a version that opens with the newer plugin?

**Comment by saltandpixel** [comment]
Yes - I would appreciate that.

**Comment by shortercode** [comment]
https://drive.google.com/file/d/129dXZJhOg30GGp6XsgOp_gCUjh0ev5GF/view?usp=sharing
