### ISSUE TITLE
Crash on empty Sprite

### ISSUE THREAD

**Issue by magalvao** [Scirra/Construct-3-bugs#1740]
## Problem description
If you create a simple project with a single empty sprite on the screen and right click it, the editor crashes.

## Attach a .c3p
https://drive.google.com/file/d/1MixlQKbGxubiHQx9ZmlghWqXb_GKvspT/view?usp=sharing

## Steps to reproduce
1. Create a new project
2. Add a sprite, with no graphics
3. Right Click the sprite

## Observed result
Editor crash.

## Expected result
I would expect to see the options for the sprite object without seeing a crash

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: Promise.resolve is not a function @ TypeError: Promise.resolve is not a function at ǃ_.ǃ_o.ǃ_Kj.ǃbV (https://editor.construct.net/r107-2/main.js:2:370591) at ǃ_.ǃ_o.ǃ_Kj.ǃ_kl (https://editor.construct.net/r107-2/main.js:2:372737) at ǃ_.ǃ_o.ǃ_Kj.ǃPx (https://editor.construct.net/r107-2/main.js:2:372784) at new ǃ_.ǃ_o.ǃQ$.ǃ_lM (https://editor.construct.net/r107-2/main.js:52:34798) at Function.ǃ_.ǃK (https://editor.construct.net/r107-2/main.js:2:141350) at ǃ_.ǃ_o.ǃQ$.ǃQY (https://editor.construct.net/r107-2/main.js:52:26828) at window.ǃsc.ǃbna (https://editor.construct.net/r107-2/components/editors/layoutView/layoutView.js:1:11705) at window.ǃsc.ǃ_l (https://editor.construct.net/r107-2/components/editors/layoutView/layoutView.js:1:11540) at HTMLDivElement.ǃ_I.ǃ_.ǃ_y.ǃ_.ǃ_P.ǃ_a (https://editor.construct.net/r107-2/components/editors/layoutView/layoutView.js:1:4307) at EventHandler.fire (chrome-extension://hhojmcideegachlhfgfdhailpfhgknjm/web_accessible_resources/index.js:79:16)
Stack: TypeError: Promise.resolve is not a function at ǃ_.ǃ_o.ǃ_Kj.ǃbV (https://editor.construct.net/r107-2/main.js:2:370591) at ǃ_.ǃ_o.ǃ_Kj.ǃ_kl (https://editor.construct.net/r107-2/main.js:2:372737) at ǃ_.ǃ_o.ǃ_Kj.ǃPx (https://editor.construct.net/r107-2/main.js:2:372784) at new ǃ_.ǃ_o.ǃQ$.ǃ_lM (https://editor.construct.net/r107-2/main.js:52:34798) at Function.ǃ_.ǃK (https://editor.construct.net/r107-2/main.js:2:141350) at ǃ_.ǃ_o.ǃQ$.ǃQY (https://editor.construct.net/r107-2/main.js:52:26828) at window.ǃsc.ǃbna (https://editor.construct.net/r107-2/components/editors/layoutView/layoutView.js:1:11705) at window.ǃsc.ǃ_l (https://editor.construct.net/r107-2/components/editors/layoutView/layoutView.js:1:11540) at HTMLDivElement.ǃ_I.ǃ_.ǃ_y.ǃ_.ǃ_P.ǃ_a (https://editor.construct.net/r107-2/components/editors/layoutView/layoutView.js:1:4307) at EventHandler.fire (chrome-extension://hhojmcideegachlhfgfdhailpfhgknjm/web_accessible_resources/index.js:79:16)
Construct 3 version: r107.2
URL: https://editor.construct.net/r107-2/
Date: Tue Jun 26 2018 18:11:23 GMT-0300 (Horário Padrão de Brasília)
Uptime: 12.6 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r107.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by magalvao** [comment]
Closing. Found the root cause.

A chrome extension called "Enable right click" was causing some type of conflict.
Leaving what happened here for anyone with the same issue, and for the Scirra Team to handle the error properly if desired.
