### ISSUE TITLE
Displays Oops! Something went wrong error

### ISSUE THREAD

**Issue by vundurty** [Scirra/Construct-3-bugs#2044]
## Problem description
Displays Oops! Something went wrong error when I try to open a project

Just opening the project produces the error

## Attach a .c3p
https://drive.google.com/file/d/1bzdP37eG5u9D_vv6-6elve53e-QEFq1m/view?usp=sharing

## Steps to reproduce

1.Just opening the project produces the error
2.
3.

## Observed result
Please check the screenshot
https://drive.google.com/file/d/1hpQXJOti_jH36El-Z3aTio4ywtNAL7Ef/view?usp=sharing

Please check the screenshot
https://drive.google.com/file/d/1hpQXJOti_jH36El-Z3aTio4ywtNAL7Ef/view?usp=sharing

## Expected result
Should open the project

Should open the project

## Affected browsers

* Chrome: yes
* Firefox: didn't try
* Edge: no
* Safari: didn't try

## System details

<details><summary>View details</summary>
Please check the below error message

You will need below addons to open the file
gameanalytics-
https://app.box.com/s/9lqek9bmkpsgkrmmg37ygvo6ft3njyno
Firebase API V3-
https://app.box.com/s/14jmhyxr5s5igxkqhemuc6orrmu8znx7
Firebase Authentication-
https://app.box.com/s/im4jkvrjqmv7eyqtwexw33gvxboqfz4s
Firebase ItemTable-
https://app.box.com/s/hw69bxiam1h9ee37fpio29qz7cdzbcct
SocialSharingPlugin
https://app.box.com/s/563wkt4mbaq4vhdm6a822hthunjj5te0
cranberrygame_CordovaInAppBrowser_1.0.5-
https://app.box.com/s/qjoxujv3soxqx9rx8g6u9jaz61f75mxu

PASTE HERE
Error report information
Type: unhandled exception
File: https://editor.construct.net/r111/components/editors/layoutView/layoutView.js, line 1, col 38890
Message: Uncaught Error: failed to parse CSS property '--layoutview-margin-color' color value: 
Stack: Error: failed to parse CSS property '--layoutview-margin-color' color value: at window.ǃrU.ǃad (https://editor.construct.net/r111/components/editors/layoutView/layoutView.js:1:38896) at i.ǃcz (https://editor.construct.net/r111/main.js:80:242180) at window.ǃrU.ǃwv (https://editor.construct.net/r111/components/editors/layoutView/layoutView.js:1:7097) at ǃwc (https://editor.construct.net/r111/components/editors/layoutView/layoutView.js:1:1811)
Construct 3 version: r111
URL: https://editor.construct.net/index.html
Date: Sat Sep 15 2018 20:49:43 GMT+0530 (India Standard Time)
Uptime: 125.9 s

Platform information
Browser: Chrome
Browser version: 69.0.3497.92
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
C3 release: r111 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Do you have a custom theme?

**Comment by vundurty** [comment]
No, I don't have any custom theme.

**Comment by shortercode** [comment]
I'm afraid I don't see any error in my current development build or r111. By the looks of the error it looks like one of your stylesheets has been changed, hence why I thought you had a custom theme. Which built in theme are you using ( default/ light/ dark )? Do you have this issue with any project or just the one you provided?

Could you try to reproduce this in an incognito window please?

**Comment by vundurty** [comment]
I'm using the default theme. 

If the project has multiple sheets open on the startup I'm getting the error. I tried on Edge I was able to open the project, closed the sheets and saved the project then I tried opening on Chrome. I'm able to open it now.
