### ISSUE TITLE
Error opening project. Crashes.

### ISSUE THREAD

**Issue by cjl014** [Scirra/Construct-3-bugs#2378]
## Problem description

Opening from my cloud project on Google Drive crashes and produces an error report.

## Steps to reproduce

1.
2.
3.

## Observed result

Error report popup.

## Affected browsers/platforms
All

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE
Error report information
Type: unhandled rejection
Reason: Error: missing condition id 'ondisconnected24' @ Error: missing condition id 'ondisconnected24' at window.ǃvfK.ǃwL (https://editor.construct.net/r120/main.js:81:318618) at window.ǃvrN.ǃwL (https://editor.construct.net/r120/main.js:63:95527) at Function.ǃuO (https://editor.construct.net/r120/main.js:81:303362) at t.ǃDq (https://editor.construct.net/r120/main.js:81:296934) at Function.ǃuF (https://editor.construct.net/r120/main.js:81:276334) at t.ǃvpv (https://editor.construct.net/r120/main.js:81:280441) at t.ǃDq (https://editor.construct.net/r120/main.js:81:297001) at Function.ǃuF (https://editor.construct.net/r120/main.js:81:276334) at e.ǃvpv (https://editor.construct.net/r120/main.js:81:280441) at e.ǃDq (https://editor.construct.net/r120/main.js:81:290904)
Stack: Error: missing condition id 'ondisconnected24' at window.ǃvfK.ǃwL (https://editor.construct.net/r120/main.js:81:318618) at window.ǃvrN.ǃwL (https://editor.construct.net/r120/main.js:63:95527) at Function.ǃuO (https://editor.construct.net/r120/main.js:81:303362) at t.ǃDq (https://editor.construct.net/r120/main.js:81:296934) at Function.ǃuF (https://editor.construct.net/r120/main.js:81:276334) at t.ǃvpv (https://editor.construct.net/r120/main.js:81:280441) at t.ǃDq (https://editor.construct.net/r120/main.js:81:297001) at Function.ǃuF (https://editor.construct.net/r120/main.js:81:276334) at e.ǃvpv (https://editor.construct.net/r120/main.js:81:280441) at e.ǃDq (https://editor.construct.net/r120/main.js:81:290904)
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Tue Nov 27 2018 19:38:04 GMT-0500 (Eastern Standard Time)
Uptime: 842.9 s

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by shortercode** [comment]
This appears to be an issue reading the project as opposed to a cloud issue. Do you recall what changes you made prior to saving it last?

**Comment by shortercode** [comment]
Please you could provide the project that causes this issue? You can download a project as a file from the cloud dialog by right clicking the project and selecting "download file" if you do not wish to share this project publicly you can email directly to us.

Also could you confirm by which method you are using to open this file? E.G. recent projects on start page, recent project in menu, cloud dialog etc.

**Comment by cjl014** [comment]
The last changes were event conditions from a third-party plugin called Photon.  The error id 'ondisconnected24' was most-likely when I added the "on disconnected" condition/listener. I saved it. Then I went on another computer and tried to open, that's when it gave the error.
So, I downloaded the plugin from the Photon website again.....uninstalled the add-on on construct.net ..... installed the plugin again....and now it is working with no errors.
I'm guessing an earlier version of the plugin was installed on my second computer and my main computer had the up-to-date version. Either that or something else crazy happened (doubt it).
Sorry for the inconvenience.

**Comment by shortercode** [comment]
The condition ID is a little confusing, I'm not sure why it has a number behind it... but it could be they added a new version of the condition and decided to add a number to the condition id to differentiate it.

I'm glad that you've solved your problem, but I'm still concerned that it caused a crash. I've attempted to trigger this by manually modifying project files and the editor hasn't crashed for me.

I had a look and the addon seems to be behind an account login so I probably can't replicate this anyway but it's frustrating.

I'm going to close this issue, if it becomes a problem someone will report it again. Hopefully with a replication that I can produce. Thanks for reporting it anyway.
