### ISSUE TITLE
"Unhandled rejection" when importing big C2 game

### ISSUE THREAD

**Issue by CureUnlovely** [Scirra/Construct-3-bugs#2416]
## Problem description
My C2 game is fairly large in size. It uses only one third party plugin - Moveto by rex rainbow. I installed the C3 counterpart of this plugin and then imported my capx game into C3. C3 gave me an error and would not let me edit or preview the project. However, it did let me save it as a c3p file. Opening that c3p file gives the same error as when I import the original .capx file. The capx file still works just fine in the lastest version of C2.
bug report:
Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.ǃv.ǃNb (https://editor.construct.net/r120/main.js:2:108973) at Function.ǃv.ǃV$P (https://editor.construct.net/r120/main.js:2:171572) at window.ǃeGz.ǃeSv (https://editor.construct.net/r120/main.js:81:394765) at window.ǃeGz.ǃeG$ (https://editor.construct.net/r120/main.js:81:394624) at window.ǃrD.ǃeG$ (https://editor.construct.net/r120/main.js:81:359355) at window.ǃrD.ǃeGM (https://editor.construct.net/r120/main.js:81:359097) at window.ǃrD.ǃMl (https://editor.construct.net/r120/main.js:81:359162) at t.ǃvmV (https://editor.construct.net/r120/main.js:81:66709) at t.ǃvxp (https://editor.construct.net/r120/main.js:81:66681) at Object.ǃv.ǃcS [as ǃVHi] (https://editor.construct.net/r120/main.js:81:66564)
Stack: TypeError: expected string at Function.ǃv.ǃNb (https://editor.construct.net/r120/main.js:2:108973) at Function.ǃv.ǃV$P (https://editor.construct.net/r120/main.js:2:171572) at window.ǃeGz.ǃeSv (https://editor.construct.net/r120/main.js:81:394765) at window.ǃeGz.ǃeG$ (https://editor.construct.net/r120/main.js:81:394624) at window.ǃrD.ǃeG$ (https://editor.construct.net/r120/main.js:81:359355) at window.ǃrD.ǃeGM (https://editor.construct.net/r120/main.js:81:359097) at window.ǃrD.ǃMl (https://editor.construct.net/r120/main.js:81:359162) at t.ǃvmV (https://editor.construct.net/r120/main.js:81:66709) at t.ǃvxp (https://editor.construct.net/r120/main.js:81:66681) at Object.ǃv.ǃcS [as ǃVHi] (https://editor.construct.net/r120/main.js:81:66564)
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Fri Dec 07 2018 14:58:11 GMT-0500 (Eastern Standard Time)
Uptime: 3439.1 s

Platform information
Browser: NW.js
Browser version: 0.35.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.0 (like Chrome/71.0.3578.80)
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Attach a .c3p

c3p: http://biancagames.com/123.c3p
Capx: https://curelovelywarrior.itch.io/lovely-warriors-of-friendship (download on page)

## Steps to reproduce

1. Open the project in C3.

## Observed result

I get the error in the above bug report. Screenshot: http://biancagames.com/c3bug1.jpg

## Expected result

I want to be able to open my C2 game in C3.

Hope I provided the details right! :)

**Comment by CureUnlovely** [comment]
Update:
Problem happens only in Desktop version. Browser version is able to open my game.
Even if I update to beta r129, Desktop version still will not open my game.

(btw, just my own random feedback thoughts: I much prefer the desktop version over the browser version)

:)

**Comment by AshleyScirra** [comment]
Hmm, with the fix there seems to be another issue with building spritesheets getting stuck. It looks like there's one sprite with several thousand animation frames... @CureUnlovely do you know which object that would be?

**Comment by CureUnlovely** [comment]
"playerskin"
It has over 600+ animations, let alone frames. It's where the animations for all the characters are stored (it's a huge crossover with 250+ characters)
"playerdead" is probably rather big also.
My game has always had an issue with being big and making C2 run slow but it was still manageable and would still work ultimately.
:)
thanks for the help, btw! <3

**Comment by CureUnlovely** [comment]
And... another thing I should probably mention, just in case it's useful. The only browser my game worked in for C2 preview mode was firefox, all the rest would hang or crash. I always assumed this was due to the game being big. NW.JS preview mode didn't work even though that's what my game is exported and built with. However C3 browser version, for me, my game seemingly worked in chrome for me.

**Comment by AshleyScirra** [comment]
Woah, it looks like "playerskin" has over 10,000 animation frames 😲 I think that's the most I've ever seen in a single object... FYI this is really poor for memory management, since Construct either loads sprites entirely or not at all. So no matter what skin the player uses, it loads *all* 10,000 animation frames in to memory. These really should be separate Sprite objects. Families let you use the same events across different sprites, so it should still be perfectly manageable to design the game that way.

C3 ought to be more efficient at handling large projects, but I've noticed a couple of issues when working with this one, so I'll take a look at making some changes to improve how it handles such large projects. C3 should also be much better at handling large projects in preview mode, since the new in-editor spritesheeting helps avoid running in to a limit in the Windows OS of allowing a maximum of 10,000 images (and your project appears to use nearly 50,000!), and the new C3 runtime has improvements to save memory with such large projects too, as well as speed up loading.

BTW if you notice any unicode issues with C3, please file issues for them as well - it ought to work fine everywhere... but sometimes it breaks for reasons out of our control (e.g. hosting on web servers that don't understand unicode filenames).

**Comment by CureUnlovely** [comment]
Thanks a whole bunch! I figured what you describe in the first paragraph was a problem, and even thought about what you say is the solution, it's just... so much work the idea of changing it once the project was already largely underway makes me mentally overwhelmed. And since it only affected preview mode, and the exported game still worked okay, I still didn't change it. I would still prefer not to have to change it now, but I will remember your advice for future projects. I do look forward to whatever changes you make that will help my project out. :)

**Comment by CureUnlovely** [comment]
I updated to version 230 and my game now opens in the desktop version. I have control over the editor, however the bottom left corner says "building spritesheets (2 remaining)". Will this break anything or is it just a graphical glitch in the editor? screenshot: http://biancagames.com/sprs.png

**Comment by AshleyScirra** [comment]
The sprite with 10,000 frames is hitting a worst-case-scenario in the spritesheet building algorithm. It will eventually complete, but you have to leave it for absolutely ages (minutes on my machine, possibly even longer on slower systems). I've done some work to speed it up for the next release so it should finish in at least <30sec. But it is very tough for the engine to deal with such an extreme case, I'm not sure we'll be able to make it much faster than that.

**Comment by CureUnlovely** [comment]
But what happens if I use the editor before it's completed?
Like I said, I have control over the editor despite it showing this message. I even checked playerskin and everything appears to be there.

**Comment by AshleyScirra** [comment]
To be honest, I don't know. Every project I've ever seen or tested with completed that within 1 second...

**Comment by CureUnlovely** [comment]
Alright, well nonetheless, thanks for the help!
<3
