### ISSUE TITLE
[HELP] NEW VERSION CAN'T PREVIEW MY PROJECT!

### ISSUE THREAD

**Issue by tuzke** [Scirra/Construct-3-bugs#2429]
new version can't preview my project !!!!
`Error report information
Type: assertion failure
Message: expected content
Stack: Error at Function.ǃO.ǃZyz (https://editor.construct.net/r130/main.js:2:142882) at e (https://editor.construct.net/r130/main.js:2:104265) at window.assert (https://editor.construct.net/r130/main.js:2:104590) at window.ǃOQa.ǃOuQ (https://editor.construct.net/r130/main.js:81:118084) at window.ǃOvj.ǃOuI (https://editor.construct.net/r130/main.js:81:112999) at window.ǃOvj.ǃOur (https://editor.construct.net/r130/main.js:81:112375)
Construct 3 version: r130
URL: https://editor.construct.net/r130/
Date: Tue Dec 11 2018 10:58:18 GMT+0700 (Indochina Time)
Uptime: 40.6 s

Platform information
Browser: Chrome
Browser version: 70.0.3538.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
C3 release: r130 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 740 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context`

`/r130/main.js:2 Assertion failure: expected content

Stack trace:
Error
    at Function.ǃO.ǃZyz (https://editor.construct.net/r130/main.js:2:142882)
    at e (https://editor.construct.net/r130/main.js:2:104265)
    at window.assert (https://editor.construct.net/r130/main.js:2:104590)
    at window.ǃOQa.ǃOuQ (https://editor.construct.net/r130/main.js:81:118084)
    at window.ǃOvj.ǃOuI (https://editor.construct.net/r130/main.js:81:112999)
    at window.ǃOvj.ǃOur (https://editor.construct.net/r130/main.js:81:112375)
e @ /r130/main.js:2
/r130/main.js:2 Assertion failure: expected content

Stack trace:
Error
    at Function.ǃO.ǃZyz (https://editor.construct.net/r130/main.js:2:142882)
    at e (https://editor.construct.net/r130/main.js:2:104265)
    at window.assert (https://editor.construct.net/r130/main.js:2:104590)
    at window.ǃOQa.ǃOSl (https://editor.construct.net/r130/main.js:81:118810)
    at window.ǃOvj.ǃOuI (https://editor.construct.net/r130/main.js:81:113056)
    at window.ǃOvj.ǃOur (https://editor.construct.net/r130/main.js:81:112375)
e @ /r130/main.js:2
/r130/main.js:74 Error starting preview:  TypeError: unexpected type
    at Function.ǃO.ǃZg (/r130/main.js:2)
    at Function.ǃO.ǃZ$_ (/r130/main.js:2)
    at Object.ǃOux.e.ǃP$ [as ǃZLz] (/r130/main.js:81)
ǃODE @ /r130/main.js:74
The FetchEvent for "https://editor.construct.net/r130/" resulted in a network error response: the promise was rejected.
Promise.catch (async)
(anonymous) @ sw.js:444
sw.js:397 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at HandleFetch (sw.js:397)`

When I go back to the old version 129, it works :/

**Comment by AshleyScirra** [comment]
I'm afraid we can't help without more information. If you don't want to share your project email it to ashley@scirra.com and I'll take a look.
