### ISSUE TITLE
Animation editor crashes when the crop tool is used

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#2565]
## Problem description

I double clicked a sprite in the layout to open the Animation Editor, hit the crop button, and Construct crashed.

## Attach a .c3p

This happens in any project with a sprite.

## Steps to reproduce

1. Open a sprite in the Animation Editor
2. Hit the crop button

## Observed result

Construct crashes.

## First affected release

r135-3

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r135-3/main.js, line 177, col 295147
Message: Uncaught TypeError: Cannot read property 'clone' of null
Stack: TypeError: Cannot read property 'clone' of null at e.ǃEMQ.ǃcCU (https://editor.construct.net/r135-3/main.js:177:295147) at e.ǃEMQ.ǃcCS (https://editor.construct.net/r135-3/main.js:177:287635) at e.ǃEMQ.ǃEMK (https://editor.construct.net/r135-3/main.js:177:287175) at e.ǃE_C.t.ǃEM_ (https://editor.construct.net/r135-3/main.js:177:267555) at e.ǃE_C.t.ǃEMY (https://editor.construct.net/r135-3/main.js:177:273212) at Array.e.addEventListener (https://editor.construct.net/r135-3/main.js:177:272946) at ǃt.Event.ǃCZw.ǃCZR (https://editor.construct.net/r135-3/main.js:2:209944) at ǃt.ǃP.ǃUX.dispatchEvent (https://editor.construct.net/r135-3/main.js:2:207812) at ǃt.ǃP.ǃT.ǃtle.ǃtz_.ǃtrS (https://editor.construct.net/r135-3/main.js:2:525187) at ǃt.ǃP.ǃT.ǃtle.ǃtz_.ǃJX (https://editor.construct.net/r135-3/main.js:2:523939)
Construct 3 version: r135.3
URL: https://editor.construct.net/r135-3/
Date: Mon Jan 28 2019 11:58:28 GMT-0800 (Pacific Standard Time)
Uptime: 120.8 s

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r135.3 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GRID K120Q Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by Roguelike2018** [comment]
https://github.com/Scirra/Construct-3-bugs/issues/2562
