### ISSUE TITLE
r141 crash on open

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#2726]
## Problem description

it crash when oppening my project

## More details
<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃrMG' of undefined @ TypeError: Cannot read property 'ǃrMG' of undefined at ǃl (https://editor.construct.net/r141/main.js:2:271748) at Object.ǃJIz (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:6186) at new (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:3142) at Function.ǃX (https://editor.construct.net/r141/main.js:2:151615) at Object.ǃsL (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:709)
Stack: TypeError: Cannot read property 'ǃrMG' of undefined at ǃl (https://editor.construct.net/r141/main.js:2:271748) at Object.ǃJIz (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:6186) at new (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:3142) at Function.ǃX (https://editor.construct.net/r141/main.js:2:151615) at Object.ǃsL (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:709)
Construct 3 version: r141
URL: https://editor.construct.net/r141/
Date: Tue Mar 12 2019 12:39:26 GMT-0300 (hora estándar de Argentina)
Uptime: 11.6 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.121
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
C3 release: r141 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon(TM) RX 460 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

PASTE HERE

</details>

**Comment by kingpirux** [comment]
i found that it was for the json being open at start and it is related to the https://github.com/Scirra/Construct-3-bugs/issues/2714
