### ISSUE TITLE
C3 crash when searching event sheet

### ISSUE THREAD

**Issue by pkreemer** [Scirra/Construct-3-bugs#3010]
## Problem description
C3 IDE crashes after or during an event sheet search.

Total guess, but seems related to issue #2992
[(https://github.com/Scirra/Construct-3-bugs/issues/2992)]

## Attach a .c3p
This seems not project-specific, as every project I try will repro.  Attaching an unedited local save of Kiwi Story.

[kiwiStory_local_unedited.zip](https://github.com/Scirra/Construct-3-bugs/files/3248380/kiwiStory_local_unedited.zip)

## Steps to reproduce
No results found path:
1. Open project,
2. Open event sheet,
3. Open Find dialog (ctrl-F for me),
4. Search for any no-match text, e.g., "test".
5. Search results dialog appears,
6. Close results dialog,
7. See C3 crash.

Variant: Search w/ results found:
1. Open project,
2. Open event sheet,
3. Open Find dialog (ctrl-F for me),
4. Search for any matching text, e.g., "x".
5. See C3 crash.

## Observed result
C3 IDE crashes, with error report, Restart buttons, etc.

## Expected result
No crash.

## More details

**Affected browsers/platforms:** 
Chrome, Windows 10, 
NWjs build of C3, or standard construct.net browser

No repro on Firefox - works great there.

**First affected release:**   R151

## System details
<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r151/components/bars/findResultsBar/findResultsBar.js, line 1, col 1536
Message: Uncaught TypeError: Cannot read property 'clear' of undefined
Stack: TypeError: Cannot read property 'clear' of undefined at Object.ǃN (https://editor.construct.net/r151/components/bars/findResultsBar/findResultsBar.js:1:1536) at Array. (https://editor.construct.net/r151/main.js:159:36627) at Object.ǃpQH (https://editor.construct.net/r151/main.js:2:193479) at Object.dispatchEvent (https://editor.construct.net/r151/main.js:2:191347) at Object.ǃeQ (https://editor.construct.net/r151/main.js:2:324068) at Object.ǃeQ (https://editor.construct.net/r151/main.js:2:329315) at Object.ǃeQ (https://editor.construct.net/r151/main.js:2:340046) at Object.ǃpnG (https://editor.construct.net/r151/main.js:2:336423) at Object. (https://editor.construct.net/r151/main.js:2:338979) at Object.ǃkH (https://editor.construct.net/r151/main.js:52:23411)
Construct 3 version: r151
URL: https://editor.construct.net/r151/
Date: Mon Jun 03 2019 08:32:43 GMT-0700 (Pacific Daylight Time)
Uptime: 25.8 s

Platform information
Browser: NW.js
Browser version: 0.38.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
C3 release: r151 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by pkreemer** [comment]
Fixed on R152, thanks!

**Comment by pkreemer** [comment]
closing, from my side-
