### ISSUE TITLE
Crash on attempting to open a Timeline in an inactive project

### ISSUE THREAD

**Issue by Valettus** [Scirra/Construct-3-bugs#3346]
## Problem description

Construct crashes when two projects with at least one Timeline are open and you try to open a timeline in the inactive project.

## Attach a .c3p

https://www.dropbox.com/s/2u4zgpwin6kf8bc/TimelineCrash.c3p?dl=1

## Steps to reproduce

1. Open the attached project twice (or create two empty projects and add a timeline to both)
2. Double click the Timeline in the inactive project

The crash only happens when both open projects have a Timeline.

## Observed result

Crash

## Expected result

Change the active project and open the selected Timeline.

## More details

**Affected browsers/platforms:** Tested on Chrome and Firefox

**First affected release:** r164.3

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: timeline does not belong to project
Stack: Error at Function.ǃa.ǃaNp (https://editor.construct.net/r164-3/main.js:2:124229) at e (https://editor.construct.net/r164-3/main.js:2:85002) at window.assert (https://editor.construct.net/r164-3/main.js:2:85332) at e.ǃouU (https://editor.construct.net/r164-3/projectResources.js:1:60640) at t.ǃwUG (https://editor.construct.net/r164-3/components/bars/timelineBar/timelineBar.js:1:4926) at t.ǃhc (https://editor.construct.net/r164-3/components/bars/timelineBar/timelineBar.js:1:5990) at Function.ǃolF (https://editor.construct.net/r164-3/components/bars/timelineBar/timelineBar.js:1:7757) at window.ǃwrV.ǃolF (https://editor.construct.net/r164-3/main.js:210:79792) at window.ǃodt.ǃodt.ǃonq (https://editor.construct.net/r164-3/components/bars/projectBar/projectBar.js:24:11138) at window.ǃodt.ǃoSq (https://editor.construct.net/r164-3/components/bars/projectBar/projectBar.js:1:9344)
Construct 3 version: r164.3
URL: https://editor.construct.net/
Date: Wed Sep 18 2019 09:39:31 GMT-0400 (Eastern Daylight Time)
Uptime: 402.3 s

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r164.3 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon (TM) RX 570 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
