### ISSUE TITLE
Project won't open

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3539]
## Problem description

I can't open my project. I got the error below:

**Desktop Version:** 

Error report information
Type: assertion failure
Message: project still loading
Stack: Error at Function.ǃGFS (https://editor.construct.net/r179/main.js:2:125979) at e (https://editor.construct.net/r179/main.js:2:85095) at https://editor.construct.net/r179/main.js:2:85425 at Object.ǃNJq (https://editor.construct.net/r179/main.js:210:98870) at Object.ǃNJc (https://editor.construct.net/r179/main.js:210:95529)
Construct 3 version: r179
URL: https://editor.construct.net/r179/
Date: Tue Dec 10 2019 22:34:27 GMT+0300 (GMT+03:00)
Uptime: 4.5 s

**Chrome:** 

Error report information
Type: unhandled rejection
Reason: Error: invalid function name 'select' @ Error: invalid function name 'select' at t.ǃSSP (https://editor.construct.net/r179/projectResources.js:1:306706) at t.ǃpt (https://editor.construct.net/r179/projectResources.js:1:306620) at window.ǃJuy.ǃSSU (https://editor.construct.net/r179/projectResources.js:1:331274) at t.accept (https://editor.construct.net/r179/projectResources.js:1:260872) at t.accept (https://editor.construct.net/r179/projectResources.js:1:297126) at t.ǃSSn (https://editor.construct.net/r179/projectResources.js:1:282925) at t.accept (https://editor.construct.net/r179/projectResources.js:1:260888) at t.ǃSSn (https://editor.construct.net/r179/projectResources.js:1:268206) at t.ǃSSn (https://editor.construct.net/r179/projectResources.js:1:282970) at t.accept (https://editor.construct.net/r179/projectResources.js:1:260888)
Stack: Error: invalid function name 'select' at t.ǃSSP (https://editor.construct.net/r179/projectResources.js:1:306706) at t.ǃpt (https://editor.construct.net/r179/projectResources.js:1:306620) at window.ǃJuy.ǃSSU (https://editor.construct.net/r179/projectResources.js:1:331274) at t.accept (https://editor.construct.net/r179/projectResources.js:1:260872) at t.accept (https://editor.construct.net/r179/projectResources.js:1:297126) at t.ǃSSn (https://editor.construct.net/r179/projectResources.js:1:282925) at t.accept (https://editor.construct.net/r179/projectResources.js:1:260888) at t.ǃSSn (https://editor.construct.net/r179/projectResources.js:1:268206) at t.ǃSSn (https://editor.construct.net/r179/projectResources.js:1:282970) at t.accept (https://editor.construct.net/r179/projectResources.js:1:260888)
Construct 3 version: r179
URL: https://editor.construct.net/r179/
Date: Tue Dec 10 2019 22:38:06 GMT+0300 (GMT+03:00)
Uptime: 11.6 s

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r179 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by bilgekaan** [comment]
A function was misnamed, I fixed it with notepad.
