### ISSUE TITLE
Timeline 

### ISSUE THREAD

**Issue by 234626** [Scirra/Construct-3-bugs#3887]
## Problem description
Just a heads-up; the Timeline crashes in the latest beta version (r201).

## Steps to reproduce
1. Open any project
2. Add a Timeline
3. Dock the Timeline to the Top or Bottom areas
4. Attempt to add an object (sprite)

## Observed result
Error appears (Crash report).

## More details
**Affected browsers/platforms:** 
Detected in Windows 10 and 8.1 64bit using Chrome, Firefox, Opera and the Desktop standalone build with either the default visual theme or from a third-party.

**First affected release:** 
Only occurs in r201, ..r200, r199, r198 are working fine.

## System details
<details><summary>View detailed report 1</summary>

Error report information

Type: unhandled rejection
Reason: Error: e is undefined @ ǃhzu@https://editor.construct.net/r201/projectResources.js:1:543037 ǃhOc@https://editor.construct.net/r201/projectResources.js:1:546396 ǃhOy@https://editor.construct.net/r201/projectResources.js:1:504994 ǃhAg@https://editor.construct.net/r201/projectResources.js:1:503638 ǃhjm@https://editor.construct.net/r201/projectResources.js:1:501488 n@https://editor.construct.net/r201/projectResources.js:1:494147 d.ǃF@https://editor.construct.net/r201/main.js:2:129085 ǃhAh@https://editor.construct.net/r201/projectResources.js:1:465225 ǃeLp@https://editor.construct.net/r201/projectResources.js:1:465436 e.ǃfbX/<@https://editor.construct.net/r201/components/bars/timelineBar/timelineBar.js:1:12798
Stack: ǃhzu@https://editor.construct.net/r201/projectResources.js:1:543037 ǃhOc@https://editor.construct.net/r201/projectResources.js:1:546396 ǃhOy@https://editor.construct.net/r201/projectResources.js:1:504994 ǃhAg@https://editor.construct.net/r201/projectResources.js:1:503638 ǃhjm@https://editor.construct.net/r201/projectResources.js:1:501488 n@https://editor.construct.net/r201/projectResources.js:1:494147 d.ǃF@https://editor.construct.net/r201/main.js:2:129085 ǃhAh@https://editor.construct.net/r201/projectResources.js:1:465225 ǃeLp@https://editor.construct.net/r201/projectResources.js:1:465436 e.ǃfbX/<@https://editor.construct.net/r201/components/bars/timelineBar/timelineBar.js:1:12798
Construct 3 version: r201
URL: https://editor.construct.net/r201/
Date: Wed May 27 2020 06:59:04 GMT+0800 (Australian Western Standard Time)
Uptime: 33.1 s
Platform information

Browser: Firefox
Browser version: 76.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
C3 release: r201 (beta)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

<details><summary>View detailed report 2</summary>
Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃwh' of undefined @ TypeError: Cannot read property 'ǃwh' of undefined at Object.ǃhzu (https://editor.construct.net/r201/projectResources.js:1:543040) at Function.ǃhOc (https://editor.construct.net/r201/projectResources.js:1:546396) at n.ǃhOy (https://editor.construct.net/r201/projectResources.js:1:504994) at n.ǃhAg (https://editor.construct.net/r201/projectResources.js:1:503638) at n.ǃhjm (https://editor.construct.net/r201/projectResources.js:1:501488) at new n (https://editor.construct.net/r201/projectResources.js:1:494147) at Function.d.ǃF (https://editor.construct.net/r201/main.js:2:129085) at o.ǃhAh (https://editor.construct.net/r201/projectResources.js:1:465225) at o.ǃeLp (https://editor.construct.net/r201/projectResources.js:1:465436) at https://editor.construct.net/r201/components/bars/timelineBar/timelineBar.js:1:12798
Stack: TypeError: Cannot read property 'ǃwh' of undefined at Object.ǃhzu (https://editor.construct.net/r201/projectResources.js:1:543040) at Function.ǃhOc (https://editor.construct.net/r201/projectResources.js:1:546396) at n.ǃhOy (https://editor.construct.net/r201/projectResources.js:1:504994) at n.ǃhAg (https://editor.construct.net/r201/projectResources.js:1:503638) at n.ǃhjm (https://editor.construct.net/r201/projectResources.js:1:501488) at new n (https://editor.construct.net/r201/projectResources.js:1:494147) at Function.d.ǃF (https://editor.construct.net/r201/main.js:2:129085) at o.ǃhAh (https://editor.construct.net/r201/projectResources.js:1:465225) at o.ǃeLp (https://editor.construct.net/r201/projectResources.js:1:465436) at https://editor.construct.net/r201/components/bars/timelineBar/timelineBar.js:1:12798
Construct 3 version: r201
URL: https://editor.construct.net/r201/
Date: Wed May 27 2020 07:33:27 GMT+0800 (Australian Western Standard Time)
Uptime: 27.1 s

Platform information
Browser: Chrome
Browser version: 83.0.4103.61
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
C3 release: r201 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2
</details>

**Comment by 234626** [comment]
https://github.com/Scirra/Construct-3-bugs/issues/3876 reported in their comments that this has already been fixed within the next beta. Closing issue.
