### ISSUE TITLE
android export error

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#3933]
Good day I can't sign the apk. Alias and Password are correct.
## Problem description
LoG:
Error: Failed to load signer "signer #1"
java.io.IOException: Failed to obtain key with alias "****" from tmp/b54996e9-82a2-4933-81db-9c3f6ea75ec3. Wrong password?
at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCertsFromKeyStore(ApkSignerTool.java:690)
at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCerts(ApkSignerTool.java:555)
at com.android.apksigner.ApkSignerTool$SignerParams.access$200(ApkSignerTool.java:509)
at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:215)
at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
Caused by: java.security.UnrecoverableKeyException: Cannot recover key
at sun.security.provider.KeyProtector.recover(KeyProtector.java:315)
at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:143)
at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:57)
at sun.security.provider.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:96)
at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(JavaKeyStore.java:71)
at java.security.KeyStore.getKey(KeyStore.java:1023)
at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCertsFromKeyStore(ApkSignerTool.java:663)
... 4 more

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise your report is impossible to investigate.

Note the error says "Wrong password?" which suggests the password is incorrect.

**Comment by ibiz3091** [comment]
> Пожалуйста, следуйте инструкциям отчета об ошибке в противном случае ваш отчет невозможно исследовать.
> 
> Обратите внимание, что ошибка говорит " Неправильный пароль?- а это значит, что пароль неверный.

If I export to Unsigned.Release.APK and sign through the program apk-signer-1.8.5. the apk Signature goes well.

I just tried signing the apk in r198 and it was successful.
in r199, there was a change in exporting to android. After this change, I can't sign my apps.
https://www.construct.net/en/make-games/releases/beta/r199

I understand that you want detailed bug reports, but lately I've been spending more time writing bug reports than developing games, which is terrible.

**Comment by AshleyScirra** [comment]
It's probably this change:

> Android export: removed 'Key password' field since it was ignored by the Java keytool

This was a bug fix. Perhaps you were previously depending on the bug.

**Comment by ibiz3091** [comment]
> Наверное, это изменение:
> 
> > Экспорт Android: удалено поле "Пароль ключа", так как оно было проигнорировано Java keytool
> 
> Это было исправление ошибки. Возможно, вы раньше зависели от ошибки.

If this was an error, how is it related to my Key Alias and my password. What should I do next? Why is my valid password no longer valid?

**Comment by ibiz3091** [comment]
I figured it out. If the Keystore password matches the Alias password, the app is signed successfully.
