### ISSUE TITLE
Signed release apk Key password missing

### ISSUE THREAD

**Issue by C3GameDev** [Scirra/Construct-3-bugs#3949]
## Problem description

When exporting a signed release apk, in the newest stable version R204 you removed the "key password". Since that, all of my builds fail and it throws an error "wrong password..."

## Attach a .c3p

doesn't matter what project you use, it's just a signing error.

## Steps to reproduce

Open any project.
Go to Export -> signed release apk -> fill in your key (key password missing)
At the end of the build -> error (see error log below)

## Observed result

build error

## Expected result

normal build

## More details

**Affected browsers/platforms:** Android

**First affected release:** r204

## System details

<details><summary>View details</summary>

Error log:
Error: Failed to load signer "signer #1"
java.io.IOException: Failed to obtain key with alias "upload" from tmp/918f060a-d711-49c3-983c-1c234283ce7f. Wrong password?
at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCertsFromKeyStore(ApkSignerTool.java:690)
at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCerts(ApkSignerTool.java:555)
at com.android.apksigner.ApkSignerTool$SignerParams.access$200(ApkSignerTool.java:509)
at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:215)
at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
Caused by: java.security.UnrecoverableKeyException: Cannot recover key
at sun.security.provider.KeyProtector.recover(KeyProtector.java:315)
at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:143)
at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:57)
at sun.security.provider.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:96)
at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(JavaKeyStore.java:71)
at java.security.KeyStore.getKey(KeyStore.java:1023)
at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCertsFromKeyStore(ApkSignerTool.java:663)
... 4 more

</details>

**Comment by AshleyScirra** [comment]
This change was intentional, because the build tool ignores the "key" field, which caused problems on its own. I don't think we can put it back without bringing back the original problems too.

**Comment by C3GameDev** [comment]
I guess you need to use always the same keystore for google play... I never had any issues with signing my builds before. That means all users who have this problem now can't use the C3 build service anymore?

**Comment by AshleyScirra** [comment]
In the interest of avoiding duplicated discussion, please post in the forum thread for the time being: https://www.construct.net/en/forum/construct-3/general-discussion-7/having-issues-export-panel-153250

**Comment by AshleyScirra** [comment]
So I think the clincher here is the fact that keystores created elsewhere, other than in Construct, ought to work with key signing. Other tools may support setting a different key password to keystore password, so we have to support that case anyway. This also covers the case of keystores created with different key passwords in older versions of Construct that supported this. So I've added back the key password field as optional (since you don't need it if you create the keystore in a recent version of Construct). This should come in a patch release some time next week.
