### ISSUE TITLE
ZygoteInit exception on Android

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-3-bugs#3965]
## Problem description

Various android devices are failing to initiate the applications throwing an exception. This didn't failed on my phone but as I uploaded it to googleplay store, the report before launch has thrown 9 devices with problems. I'm unable to replicate this at all, I noticed this because of the automated test google runs. I believe this issue may have to do with AdMob, the last year I reported something similar on this issue: https://github.com/Scirra/Construct-3-bugs/issues/3042

I'll try to isolate the problem with more testing and help with whatever I find.

## Attach a .c3p

This is happening on an app in production, I'm unable to replicate it since my devices are limited.

## Steps to reproduce

App: https://play.google.com/store/apps/details?id=com.ppstudio.galaxyshipdefender

1. Install the app in the specified devices.
2. Run the app

## Observed result

Application gets stucked while loading, it doesn't complete therefore the app remains in the loading screen doing nothing.

## Expected result

Application must run.

## More details
Phone models that Google as shown problems in

- P8 Lite - Huawei Android 5.0
- Moto G4 Play - Android 6.0
- K3 2017 - LGE Android 6.0
- Mate 9 - Huawei Android 7.0
- Moto Z - Android 7.0

**Affected browsers/platforms:**  
Android. 
Construct 3 r204.

**First affected release:** I just noticed this, I don't know if this failed before as I haven't updated my app in over year, until now.

## System details
See example video downloaded from google play:
https://1drv.ms/v/s!AplmNxS7v_m5g_ZaFH6Eg_QODv5W9A?e=tOP7tV

<details><summary>View details</summary>

StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredConstructorInternal(Native Method)
	at java.lang.Class.getConstructor0(Class.java:2325)
	at java.lang.Class.getConstructor(Class.java:1725)
	at cEi.a(PG:6)
	at org.chromium.content.browser.selection.SmartSelectionClient.<init>(PG:5)
	at cEQ.a(Unknown Source:7)
	at org.chromium.android_webview.AwContents.e(PG:245)
	at org.chromium.android_webview.AwContents.d(PG:210)
	at org.chromium.android_webview.AwContents.<init>(PG:77)
	at to.run(PG:15)
	at aJK.a(PG:13)
	at aJL.run(Unknown Source:2)
	at org.chromium.base.task.PostTask.b(PG:16)
	at aJK.a(PG:7)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.b(PG:6)
	at com.android.webview.chromium.WebViewChromium.init(PG:105)
	at android.webkit.WebView.<init>(WebView.java:422)
	at android.webkit.WebView.<init>(WebView.java:348)
	at android.webkit.WebView.<init>(WebView.java:331)
	at android.webkit.WebView.<init>(WebView.java:318)
	at org.apache.cordova.engine.SystemWebView.<init>(SystemWebView.java:47)
	at org.apache.cordova.engine.SystemWebView.<init>(SystemWebView.java:43)
	at org.apache.cordova.engine.SystemWebViewEngine.<init>(SystemWebViewEngine.java:76)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:80)
	at org.apache.cordova.CordovaActivity.makeWebViewEngine(CordovaActivity.java:206)
	at org.apache.cordova.CordovaActivity.makeWebView(CordovaActivity.java:202)
	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:146)
	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
	at com.ppstudio.galaxyshipdefender.MainActivity.onCreate(MainActivity.java:39)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:14)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

</details>

**Comment by AshleyScirra** [comment]
This looks like a problem with Android, not Construct. It seems to be failing to create the WebView which is done by the system.

Further, as noted in the bug report guidelines, I'm afraid it's impossible to investigate issues unless you provide a sample project. We cannot investigate issues only providing compiled applications or videos. Therefore there is nothing we can do to investigate this report anyway.

I'd suggest reporting this issue to Google instead.
