### ISSUE TITLE
[r32] Crash when clicking left mouse button while middle mouse button is depressed

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#401]
## Problem description

While holding down middle mouse button down to pan with the cursor over a selected sprite, I hit the left mouse button and Construct 3 crashed.

## Attach a .c3p

[LMBplusMMBcrash.zip](https://github.com/Scirra/Construct-3-bugs/files/1040367/LMBplusMMBcrash.zip)

## Steps to reproduce

1. Create or open a project containing a sprite.
2. Left click on the sprite to select it.
3. While the cursor is over the sprite, click and hold the middle mouse button.
4. With MMB still depressed and the cursor still over the sprite, click the left mouse button.

## Observed result

Construct 3 crashes.

## Expected result

No crashes.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r32/main.js, line 2, col 256442
Message: Uncaught Error: pointer already captured
Stack: Error: pointer already captured at Function.ǃKn (https://editor.construct.net/r32/main.js:2:256448) at o.ǃws (https://editor.construct.net/r32/components/editors/layoutView/layoutView.js:1:42006) at o.ǃJh (https://editor.construct.net/r32/components/editors/layoutView/layoutView.js:1:56623) at Array.ǃKH (https://editor.construct.net/r32/components/editors/layoutView/layoutView.js:1:55757) at ǃi.Event.ǃsWX.ǃsWv (https://editor.construct.net/r32/main.js:2:253908) at window.ǃqR.dispatchEvent (https://editor.construct.net/r32/main.js:2:252562) at window.ǃqR.ǃJh (https://editor.construct.net/r32/components/editors/layoutView/layoutView.js:1:13670) at HTMLDivElement.ǃU.ǃi.ǃL.ǃi.ǃ_.ǃx (https://editor.construct.net/r32/components/editors/layoutView/layoutView.js:1:3851) at HTMLDocument. (https://editor.construct.net/r32/main.js:2:249444)
Construct 3 version: r32
URL: https://editor.construct.net/index.html
Date: Tue May 30 2017 22:37:44 GMT-0700 (Pacific Daylight Time)
Uptime: 140.3 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r32

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by 3dParadox** [comment]
Does seem to require the sprite, but I was able to reproduce it.
same "Uncaught Error: pointer already captured"
