### ISSUE TITLE
Storyboard splash Still not working

### ISSUE THREAD

**Issue by karimlahbach** [Scirra/Construct-3-bugs#4078]
## 

## Steps to reproduce

1. Just open any simple project and add 2048 X 2048 in icon folder
2. Set image parameter to storyboard Splash and set Preloader to nothing
3. Export debug apk

## Observed result
Black screen show up
and storyboard Splash not showing up

## Expected result
Storyboard splash show up
and construct 3 loader not to show up

## More details

**Affected browsers/platforms:*last chrome update* 

**First affected release:*r209* 

## System details

<details><summary>View details</summary>

i try to export using android studio project and the same problem happen

</details>

**Comment by AshleyScirra** [comment]
I developed the feature testing with the project provided in #4052. I just tried it again, and it works correctly.

**Comment by karimlahbach** [comment]
I try the same project that i provide in #4052 and the splash not show up
[TESTV2.zip](https://github.com/Scirra/Construct-3-bugs/files/4990110/TESTV2.zip) 
there is something wrong 
i test the feature with my old sony xperia Z3 android 6.0.1
this video show what happen
[Video.zip](https://github.com/Scirra/Construct-3-bugs/files/4990186/Video.zip)
the same happen when when you set preloader to nothing you get a only a black screen 
now the wired is i try to test the debug APK on Xiaomi Redmi 5 Plus and the app close before showing anything
i will try to make more test and investigation on other devices to see if this will work

**Comment by karimlahbach** [comment]
This video show exactly what happen when i try to open the app in Xioami redmi 5 plus
[Xioami redmi 5.zip](https://github.com/Scirra/Construct-3-bugs/files/4990344/Xioami.redmi.5.zip) 
The app close automatically

**Comment by karimlahbach** [comment]
Here is some updates
The Splash screen work on my google pixel 1 android 10 
i believe there is problem with older android version 
also i ask my friend to test the app on his xioami phone and the app close automatically like my xioami phone maybe there is problem with Some GPU version that causing this

**Comment by karimlahbach** [comment]
Here another update i try to use (firebase test lab) and this some result

App crashed during testing
Fatal exception
java.lang.RuntimeException: Canvas: trying to draw too large(115605504bytes) bitmap.
     FATAL EXCEPTION: main
Process: kdsfjk.ksdjfl, PID: 10952
java.lang.RuntimeException: Canvas: trying to draw too large(115605504bytes) bitmap.
	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
	at android.widget.ImageView.onDraw(ImageView.java:1367)
	at android.view.View.draw(View.java:19119)
	at android.view.View.updateDisplayListIfDirty(View.java:18069)
	at android.view.View.draw(View.java:18847)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
	at android.view.View.updateDisplayListIfDirty(View.java:18060)
	at android.view.View.draw(View.java:18847)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
	at android.view.View.updateDisplayListIfDirty(View.java:18060)
	at android.view.View.draw(View.java:18847)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
	at android.view.View.draw(View.java:19122)
	at com.android.internal.policy.DecorView.draw(DecorView.java:785)
	at android.view.View.updateDisplayListIfDirty(View.java:18069)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2980)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2794)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2347)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by karimlahbach** [comment]
The same happen with Firebase test lab 
you can try this your self ashley  : https://firebase.google.com/docs/test-lab

**Comment by karimlahbach** [comment]
in conclusion there is 2 bugs 
1- the Splash screen is not working with older android devices (for example android 6) 
2- App crunch during the opening in some devices ( wish is maybe is not construct 3 related ) still don't really know
Thank you Ashley for you work on the time you put to make construct 3 great i know dealing with bugs is something hard and time consuming 👍

**Comment by AshleyScirra** [comment]
So far I've tried a Pixel 3 running Android 10 and a Samsung Galaxy Tab A (SM-T515) running Android 9. Both worked fine. I'll try to test some further devices tomorrow.

If the splash screen only doesn't show on old Android versions, I'm not sure what we could do about that, and it doesn't seem like too severe a problem anyway - these days Android updates are much better than they used to be. According to StatCounter about 75% of devices are on Android 8+ (84% for Android 7+). So if only say Android 5-6 devices don't show a splash, it's only a small and shrinking number of old devices. Plus Android compatibility is a total nightmare. So as long as it works on the majority of modern devices I think that's probably OK.

The crash is bizarre, it doesn't seem to make any sense at all. A 2048x2048 splash fully decompressed in a standard RGBA8 format would be about 16mb. The crash message says an image is too big, and reports it as being over 100mb. So it doesn't seem like that could be caused by the splash. I've no idea what could be going on. Besides, if some devices crash showing a splash screen, what option do we have other than to not show a splash screen?

**Comment by karimlahbach** [comment]
i delete the 2048x2048 image and i try to test the app without using any splash screen 
the bad news : the crash still happen even without using any splash screen
the good news : the splash screen is not the responsible of causing the crash
i test this on xiaomi redmi 5 plus Android 8

**Comment by karimlahbach** [comment]
![Capture](https://user-images.githubusercontent.com/22240696/88830162-77639980-d1c5-11ea-8c0e-14960d992823.PNG)
i try 5 devices in FIREBASE TEST LAB
4 of them give the same erreur

**Comment by karimlahbach** [comment]
i'm non programmer i can't help to much but hope this solution help you
https://stackoverflow.com/questions/40835514/android-canvas-drawing-too-large-bitmap

**Comment by AshleyScirra** [comment]
Construct always generates a splash image, and will use a default if there's no splash image, so deleting the splash image does not mean no image is used. I'll try adjusting the way we configure the splash screen and see if that helps.

**Comment by karimlahbach** [comment]
Thank you Ashley i hope that work

**Comment by AshleyScirra** [comment]
@karimlahbach - I've updated the build server with a new configuration for splash screens, which might help. The change is already live now, so if you do a new debug APK build, it will be updated. Could you check again and see if it's helped?

**Comment by karimlahbach** [comment]
it working thank you so much ashley thank you
The splash screen show up and the app not crashing
i test on Xioami redmi 5 plus 
i will try different devices to make sure that everything is ok
Thank you again

**Comment by karimlahbach** [comment]
Good news Ashley the splash screen show up on my old Xperia too ( android 6 )

**Comment by AshleyScirra** [comment]
Good news! Great, thanks for confirming.
