### ISSUE TITLE
Tiled Background with physics

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#4140]
I thought I already reported this, but can't find mention of it anywhere. After the new release, my project kept freezing at runtime. I went through the project, deleting things step by step until I ended up with just a tiled background object with the physics behaviour.

When I press play, the project freezes.

## Attach a .c3p

[Physics.zip](https://github.com/Scirra/Construct-3-bugs/files/5103733/Physics.zip)

## Steps to reproduce

I've had the project working for months. However, in the beta, it now crashes when my tiled background has physics. However, creating it from scratch doesn't appear to result in a crash, so I imagine there's something else that's the problem.

## Observed result

When trying to play the project, I just get a black screen.

## Expected result

Normally, the project loads properly.

## More details
```
99076544-caf3-412e-aa5a-cc69e1958338:4 Uncaught (in promise) Assertion failed: bd->position.IsValid(), at: Box2D_v2.3.1/Box2D/Dynamics/b2Body.cpp,27,b2Body at Error
    at Ra (https://editor.construct.net/r212/behaviors/movements/physics/c3runtime/box2d.wasm.js:23:26)
    at ___assert_fail (https://editor.construct.net/r212/behaviors/movements/physics/c3runtime/box2d.wasm.js:59:222)
    at <anonymous>:wasm-function[613]:0x28143
    at _emscripten_bind_b2World_CreateBody_1 (<anonymous>:wasm-function[224]:0x1014f)
    at b._emscripten_bind_b2World_CreateBody_1 (https://editor.construct.net/r212/behaviors/movements/physics/c3runtime/box2d.wasm.js:245:262)
    at C.CreateBody (https://editor.construct.net/r212/behaviors/movements/physics/c3runtime/box2d.wasm.js:447:474)
    at PhysicsInstance._CreateBody (https://editor.construct.net/r212/behaviors/movements/physics/c3runtime/instance.js:7:402)
    at PhysicsInstance.PostCreate (https://editor.construct.net/r212/behaviors/movements/physics/c3runtime/instance.js:5:209)
    at BehaviorInstance.PostCreate (https://editor.construct.net/r212/preview/c3/objects/behaviorInstance.js:2:645)
    at Instance._CreateSdkInstance (https://editor.construct.net/r212/preview/c3/objects/instance.js:7:278)
```

**First affected release:** Worked in the latest stable, but broke in the latest beta (r212).

**Comment by 4demon** [comment]
Sorry, I searched and searched and couldn't find the previous report about this I posted, so assumed I didn't post it.... but then found it :(

Still, there's new info in here, such as me being unable to replicate it on a new project. It's just old projects that break.
