### ISSUE TITLE
r220 - Crash when selecting 9-Slice and Sprite objects

### ISSUE THREAD

**Issue by GeometriXza** [Scirra/Construct-3-bugs#4286]
## Problem description

Red screen crash when selecting 9-Slice and Sprite objects together.

## Attach a .c3p

[CrashTest.zip](https://github.com/Scirra/Construct-3-bugs/files/5372149/CrashTest.zip)

## Steps to reproduce

1. Create a 9-Slice Object and a Sprite Object.
2. Select both objects in a layout
3. Crash!

## Observed result

Error screen

## Expected result

Normal behaviour. I.e.: updated properties bar

## More details

**Affected browsers/platforms:** 

Browser version below

**First affected release: r220**

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js, line 71, col 287
Message: Uncaught TypeError: Cannot read property 'Ik' of null
Stack: TypeError: Cannot read property 'Ik' of null at n.RYc (https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js:71:287) at n.UQ (https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js:52:229) at n.K$b (https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js:19:523) at Array. (https://editor.construct.net/r220/components/bars/propertiesBar/propertiesBar.js:3:225) at Object.G8c (https://editor.construct.net/r220/main.js:428:387) at Object.dispatchEvent (https://editor.construct.net/r220/main.js:424:135) at Object.qia (https://editor.construct.net/r220/main.js:2094:372) at p.e2c (https://editor.construct.net/r220/components/editors/layoutView/layoutView.js:158:201) at p.sq (https://editor.construct.net/r220/components/editors/layoutView/layoutView.js:157:201) at Object.xu (https://editor.construct.net/r220/components/editors/layoutView/layoutView.js:55:124)
Construct 3 version: r220
URL: https://editor.construct.net/r220/
Date: Tue Oct 13 2020 16:40:38 GMT+0200 (South Africa Standard Time)
Uptime: 10.2 s

Platform information
Browser: Chrome
Browser version: 86.0.4240.75
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
C3 release: r220 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by avishaymizrav** [comment]
Same with tiled background

**Comment by DiegoScirra** [comment]
Duplicate of #4287
