### ISSUE TITLE
C3 bug (crash)

### ISSUE THREAD

**Issue by swad1992** [Scirra/Construct-3-bugs#438]
**Problem Description**
I can't launch C3
I can't do any action because the pop up blocks the interactions with the other elements of the editor

**Attach a Capx**
This bug doesn't concern the capx files
    
**Description of Capx**
No capx

**Steps to Reproduce Bug**
1. Just go to editor.construct.net

**Observed Result**
Red background with message
Here is the error :
`
```
Error` report information
Type: unhandled rejection
Reason: Error: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided. @ TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided. at window.ǃOPm.ǃOP$ (https://editor.construct.net/r34/main.js:61:404844) at window.ǃOPm.ǃpPf (https://editor.construct.net/r34/main.js:61:401530) at Object.n.push.ǃO.ǃ$t [as ǃpDH] (https://editor.construct.net/r34/main.js:162:20245) at n (https://editor.construct.net/r34/main.js:2:257133) at t (https://editor.construct.net/r34/main.js:2:256919)
Stack: TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided. at window.ǃOPm.ǃOP$ (https://editor.construct.net/r34/main.js:61:404844) at window.ǃOPm.ǃpPf (https://editor.construct.net/r34/main.js:61:401530) at Object.n.push.ǃO.ǃ$t [as ǃpDH] (https://editor.construct.net/r34/main.js:162:20245) at n (https://editor.construct.net/r34/main.js:2:257133) at t (https://editor.construct.net/r34/main.js:2:256919)
Construct 3 version: r34
URL: https://editor.construct.net/
Date: Sun Jun 04 2017 01:25:59 GMT+0200 (Paris, Madrid (heure d’été))
Uptime: 9.9 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r34

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
```
    
**Affected Browsers**
Chrome: (YES)

**Operating System and Service Pack**
WINDOWS 10
Chrome 58.0.3029.110 (64-bit)
    
**Construct 3 Version ID**
The last one

http://www.hostingpics.net/viewer.php?id=431716Capture.png

**Comment by swad1992** [comment]
No I have this error : 
[http://image.noelshack.com/fichiers/2017/22/1496581120-1.png](url)

**Comment by AshleyScirra** [comment]
Can you try clearing your browser cache and trying again?

**Comment by swad1992** [comment]
Nice, thank you, solved

Btw, please see this topic, I can't create topics :(
https://www.scirra.com/forum/viewtopic.php?f=146&t=192396&p=1126027#p1126027
