### ISSUE TITLE
Can't import C2 project into C3

### ISSUE THREAD

**Issue by 1mrpaul1** [Scirra/Construct-3-bugs#4807]
When trying to import C2 project to C3, always stacking on this error.
My guess is because C3 doesn't support folders with Russian letters 

This project
[Contr Heroes Arena convvv3.zip](https://github.com/Scirra/Construct-3-bugs/files/6443543/Contr.Heroes.Arena.convvv3.zip)

Error report information
Type: unhandled rejection
Reason: Error: expected a child with tag name 'animation-folder' @ Error: expected a child with tag name 'animation-folder' at Object.uk (https://editor.construct.net/r247/main.js:467:185) at Function.Dwd (https://editor.construct.net/r247/projectResources.js:137:36)
Stack: Error: expected a child with tag name 'animation-folder' at Object.uk (https://editor.construct.net/r247/main.js:467:185) at Function.Dwd (https://editor.construct.net/r247/projectResources.js:137:36)
Construct 3 version: r247
URL: https://editor.construct.net/r247/
Date: Fri May 07 2021 23:08:47 GMT+0500 (Узбекистан, стандартное время)
Uptime: 230.9 s

Platform information
Browser: Chrome
Browser version: 90.0.4430.93
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.125
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
C3 release: r247 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.15003.1004)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. There is nothing we can do unless you at least provide your project file.

**Comment by 1mrpaul1** [comment]
I added the file firstly but then realized that it is public, which isn't a good thing. Can I share it privately?

**Comment by AshleyScirra** [comment]
You can email it to me at ashley@scirra.com. However I should warn you often the problem is the C2 project is itself corrupt in some way, or it uses broken third-party addons, in which case I won't be able to help.

**Comment by 1mrpaul1** [comment]
Thank you, i sent you the archive
