### ISSUE TITLE
Playing Timelines in the editor crashes the app

### ISSUE THREAD

**Issue by EnriqueAlbirCodi** [Scirra/Construct-3-bugs#4973]
## Problem description

The editor crashes as soon as you play a timeline.

## Attach a .c3p

[TemplateMulti.zip](https://github.com/Scirra/Construct-3-bugs/files/6854438/TemplateMulti.zip)

## Steps to reproduce

1. Open a timeline in the editor
2. Play the timeline

## Observed result

The editor crashes.

## Expected result

The Timeline is played in the editor.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r257/projectResources.js, line 715, col 120
Message: Uncaught Error: no original size available
Stack: Error: no original size available at d.v_ (https://editor.construct.net/r257/projectResources.js:715:126) at d.ab (https://editor.construct.net/r257/projectResources.js:711:334) at d.MEb (https://editor.construct.net/r257/projectResources.js:699:70) at dbb (https://editor.construct.net/r257/projectResources.js:699:259) at d.Pl (https://editor.construct.net/r257/projectResources.js:700:242) at d.Lbc (https://editor.construct.net/r257/projectResources.js:722:178) at d.gf (https://editor.construct.net/r257/projectResources.js:1112:365) at d.gf (https://editor.construct.net/r257/projectResources.js:1076:470) at kPb (https://editor.construct.net/r257/components/editors/layoutView/layoutView.js:81:104)
Construct 3 version: r257
URL: https://editor.construct.net/r257/
Date: Wed Jul 21 2021 11:22:09 GMT+0200 (hora de verano de Europa central)
Uptime: 30.6 s

Platform information
Browser: Chrome
Browser version: 91.0.4472.164
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
C3 release: r257 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 730 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by EnriqueAlbirCodi** [comment]
Even using the Edit Mode (Pencil Icon) crashes the editor as well.this issue makes creating Timelines super frustrating because they only work at runtime.

**Comment by EnriqueAlbirCodi** [comment]
https://user-images.githubusercontent.com/58432696/126467333-245014ed-e996-4c08-abb6-679c7f969499.mp4

**Comment by DiegoScirra** [comment]
Fixed in the next beta.

**Comment by EnriqueAlbirCodi** [comment]
Thanks for the quick response.

What's the estimated launch of the next beta?
