### ISSUE TITLE
Crash while Copying Sprite Font from One Project to Another

### ISSUE THREAD

**Issue by shubhamrathi9** [Scirra/Construct-3-bugs#5038]
## Problem description

Tried copying the object from object panel to another project and it crashed.

## Steps to reproduce

1. Copy Sprite font object from one project's Object panel to another project's Object panel.
2. Crash Happens
3. Looking at it and wondering what happened

## Observed result

Shocked to the very core

## Expected result

Soothing calmness of bliss if copied properly.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'I4' of null @ TypeError: Cannot read property 'I4' of null at d.Ah (https://editor.construct.net/r260/projectResources.js:658:456) at d.ni (https://editor.construct.net/r260/projectResources.js:485:506) at d.ni (https://editor.construct.net/r260/projectResources.js:582:215) at d.bb (https://editor.construct.net/r260/projectResources.js:485:394) at d.bb (https://editor.construct.net/r260/projectResources.js:564:138) at B9a (https://editor.construct.net/r260/components/bars/projectBar/projectBar.js:26:332)
Stack: TypeError: Cannot read property 'I4' of null at d.Ah (https://editor.construct.net/r260/projectResources.js:658:456) at d.ni (https://editor.construct.net/r260/projectResources.js:485:506) at d.ni (https://editor.construct.net/r260/projectResources.js:582:215) at d.bb (https://editor.construct.net/r260/projectResources.js:485:394) at d.bb (https://editor.construct.net/r260/projectResources.js:564:138) at B9a (https://editor.construct.net/r260/components/bars/projectBar/projectBar.js:26:332)
Construct 3 version: r260
URL: https://editor.construct.net/
Date: Thu Sep 02 2021 10:28:24 GMT+0530 (India Standard Time)
Uptime: 875.4 s

Platform information
Browser: Chrome
Browser version: 92.0.4515.159
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
C3 release: r260 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0, D3D11-20.19.15.4835)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by shubhamrathi9** [comment]
The issue may have happened due to a third party plugin
