### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by Maschenko** [Scirra/Construct-3-bugs#5089]
## Problem description

When building a project for Ios (Cordova), an error with a window (popup) with logs:

Error: Platform 'ios' found in config.xml... Migrating it to package.json
Discovered platform "ios". Adding it to the project
WARNING: Applications for platform ios can not be built on this OS - linux.
Using cordova-fetch for cordova-ios@6.2.0
...
CocoaPods 1.11.2 is available.
To update use: `sudo gem install cocoapods`
For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https:1.11.2
Analyzing dependencies
[!] `GoogleAppMeasurement` requires CocoaPods version `>= 1.10.2`, which is not satisfied by your current version, `1.10.0`.
CordovaError: Promise rejected with non-error: undefined
at cordova:30:15
at processTicksAndRejections (task_queues.js:94:5)

## Attach a .c3p
–
## Steps to reproduce

1. Add to project: "MobileAdvertising" and "PlatformInformation"
2. Start building for iOS (cordova) -> XCode

## Observed result

No build occurs

Error: Platform 'ios' found in config.xml... Migrating it to package.json
Discovered platform "ios". Adding it to the project
WARNING: Applications for platform ios can not be built on this OS - linux.
Using cordova-fetch for cordova-ios@6.2.0
...
CocoaPods 1.11.2 is available.
To update use: `sudo gem install cocoapods`
For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https:/~~/1.11.2
Analyzing dependencies
[!] `GoogleAppMeasurement` requires CocoaPods version `>= 1.10.2`, which is not satisfied by your current version, `1.10.0`.
CordovaError: Promise rejected with non-error: undefined
at /cordova:30:15
at processTicksAndRejections (/task_queues.js:94:5)

## Expected result

Successful build for iOS -> XCode

## More details

When you add to the project ("MobileAdvertising" and "PlatformInformation") it does not build for iOS

## System details

<details><summary>View details</summary>

Error: Platform 'ios' found in config.xml... Migrating it to package.json
Discovered platform "ios". Adding it to the project
WARNING: Applications for platform ios can not be built on this OS - linux.
Using cordova-fetch for cordova-ios@6.2.0
Adding ios project...
Creating Cordova project for the iOS platform:
Path: ~~/ios
Package: com.name.name
Name: NameTest
iOS project created with cordova-ios@6.2.0
Plugin 'cordova-plugin-vibration' found in config.xml... Migrating it to package.json
Plugin 'admob-plus-cordova' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-consent' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-device' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-add-swift-support' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-idfa' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-nativestorage' found in config.xml... Migrating it to package.json
Plugin 'construct-mobile-export' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-splashscreen' found in config.xml... Migrating it to package.json
Discovered plugin "cordova-plugin-vibration". Adding it to the project
Installing "cordova-plugin-vibration" for ios
Discovered plugin "admob-plus-cordova". Adding it to the project
Installing "admob-plus-cordova" for ios
Discovered plugin "cordova-plugin-consent". Adding it to the project
Installing "cordova-plugin-consent" for ios
Discovered plugin "cordova-plugin-device". Adding it to the project
Installing "cordova-plugin-device" for ios
Discovered plugin "cordova-plugin-add-swift-support". Adding it to the project
Installing "cordova-plugin-add-swift-support" for ios
Discovered plugin "cordova-plugin-idfa". Adding it to the project
Installing "cordova-plugin-idfa" for ios
Discovered plugin "cordova-plugin-nativestorage". Adding it to the project
Installing "cordova-plugin-nativestorage" for ios
Discovered plugin "construct-mobile-export". Adding it to the project
Installing "construct-mobile-export" for ios
Discovered plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Discovered plugin "cordova-plugin-splashscreen". Adding it to the project
Installing "cordova-plugin-splashscreen" for ios
Running manual pod update
Pod update failed
Update all pods
Updating local specs repositories
 
CocoaPods 1.11.2 is available.
To update use: `sudo gem install cocoapods`
 
For more information, see https:/blog.cocoapods.org and the CHANGELOG for this version at https:/1.11.2
 
Analyzing dependencies
[!] `GoogleAppMeasurement` requires CocoaPods version `>= 1.10.2`, which is not satisfied by your current version, `1.10.0`.
 
CordovaError: Promise rejected with non-error: undefined
at /cordova:30:15
at processTicksAndRejections (/task_queues.js:94:5)

</details>

**Comment by AshleyScirra** [comment]
Duplicate of #5088. It looks like there was a brief outage of the build service. Apologies for the inconvenience. It should be back up and running again now.

**Comment by Maschenko** [comment]
> Duplicate of #5088. It looks like there was a brief outage of the build service. Apologies for the inconvenience. It should be back up and running again now.

I tried to make a build now, the error is still there.

**Comment by AshleyScirra** [comment]
Please file a new issue following all the guidelines. We need a .c3p file attached to investigate.

**Comment by Maschenko** [comment]
I will attach here so as not to breed duplicates. [error_iOS.c3p](https://drive.google.com/file/d/1AY6s7mG442FV-PtC1hJGsdVrcFF1OWdo/view?usp=sharing)

**Comment by AshleyScirra** [comment]
It looks like a dependency in one of the Mobile Advert libraries changed. I updated the build server and it looks like it can export successfully now.
