### ISSUE TITLE
Copy Sprite and then Copy Family Crashes

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5117]
## Problem description

If copy an object that also has a Family, this Family contains only one this object. and have family instance variables. copying Family will crash.  

If copy Family directly, there is no problem.
if Family no have family behavior or family instance variables, there is no problem.

## Attach a .c3p

[A.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/7350642/A.c3p.zip)

## Steps to reproduce

**Crashes1**  
1. copy Sprite1(red) object to new project
2. copy 'Crash1' family to new project
3. Crashes

but copy 'Crash1' family directly there is no problem.
if copy 'Nothing1' family first, and then copy  'Crash1' family, there is no problem.

## More details

**Error report information:**

<details><summary>Error report information</summary>

```
Error report information
Type: unhandled exception
File: https://editor.construct.net/r267/main.js, line 931, col 65
Message: Uncaught Error: missing instance variable value
Stack: Error: missing instance variable value at d.zL (https://editor.construct.net/r267/projectResources.js:524:215) at cab (https://editor.construct.net/r267/components/bars/propertiesBar/propertiesBar.js:39:375) at g.Lf.z (https://editor.construct.net/r267/components/bars/propertiesBar/propertiesBar.js:18:472) at fh (https://editor.construct.net/r267/main.js:365:150) at Bq.g.I.kvb.Bs (https://editor.construct.net/r267/main.js:1344:310) at new Bq.g.I.kvb (https://editor.construct.net/r267/main.js:1342:328) at Function.ya.j (https://editor.construct.net/r267/main.js:931:44) at Fq.g.I.v0.Lf (https://editor.construct.net/r267/main.js:1358:100) at eab (https://editor.construct.net/r267/components/bars/propertiesBar/propertiesBar.js:18:462) at d.CCG.ba.oP (https://editor.construct.net/r267/components/bars/propertiesBar/propertiesBar.js:123:38)
Construct 3 version: r267
URL: https://editor.construct.net/r267/
Date: Fri Oct 15 2021 11:16:19 GMT+0800 (中国标准时间)
Uptime: 8.7 s

Platform information
Browser: Chrome
Browser version: 94.0.4606.81
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.5299999713897705
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
C3 release: r267 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.15.1010)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
```
</details>
  

**Affected browsers/platforms:** 

**First affected release:**  r260 - r267

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by XHXIAIEIN** [comment]
I know I should go on to add something. You can try this clipboard. I follow this order, paste it into a new project and it crashes.


Sprite: (Paste to Layout)
```
{"is-c3-clipboard-data":true,"type":"world-instances","items":[{"type":"Sprite1","properties":{"initially-visible":true,"initial-animation":"Animation 1","initial-frame":0,"enable-collisions":true,"live-preview":false},"instanceVariables":{"active":false,"id":0,"name":"","active2":false,"id2":0,"name2":""},"behaviors":{"Tween":{"properties":{"enabled":true}},"Pin":{"properties":{"destroy":false}},"Tween2":{"properties":{"enabled":true}}},"world":{"x":192,"y":288,"width":64,"height":64,"originX":0.5,"originY":0.5,"color":[1,1,1,1],"angle":0,"zElevation":0}}],"object-types":[{"name":"Sprite1","plugin-id":"Sprite","isGlobal":false,"instanceVariables":[],"behaviorTypes":[],"effectTypes":[],"animations":{"items":[{"frames":[{"width":64,"height":64,"originX":0.5,"originY":0.5,"originalSource":"","exportFormat":"png","exportQuality":0.8,"imageDataIndex":0,"useCollisionPoly":true,"duration":1}],"name":"Animation 1","isLooping":false,"isPingPong":false,"repeatCount":1,"repeatTo":0,"speed":5}],"subfolders":[],"name":"Animations"}}],"imageData":["data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAIJJREFUeF7t1wERACAMA7FNEbKRCUI+SOix5rp3zpvwWwH4AU5AB4Q7cJQgBShAAQpQIJwABjGIQQxiMIyAMYRBDGIQgxjEYDgBDGIQgxjEYBgBaxCDGMQgBjGIwXACGMQgBjGIwTAC1iAGMYhBDGIQg+EEMIhBDGIQg2EErEEM1hn8f5d1gUDQwQwAAAAASUVORK5CYII="]}
```

Family (Paste to Familes Folder)
```
{"is-c3-clipboard-data":true,"type":"families","object-types":[{"name":"Sprite1","plugin-id":"Sprite","isGlobal":false,"instanceVariables":[],"behaviorTypes":[],"effectTypes":[],"animations":{"items":[{"frames":[{"width":64,"height":64,"originX":0.5,"originY":0.5,"originalSource":"","exportFormat":"png","exportQuality":0.8,"imageDataIndex":0,"useCollisionPoly":true,"duration":1}],"name":"Animation 1","isLooping":false,"isPingPong":false,"repeatCount":1,"repeatTo":0,"speed":5}],"subfolders":[],"name":"Animations"},"ui-state":null}],"items":[{"name":"Crash1","plugin-id":"Sprite","instanceVariables":[{"name":"active","type":"boolean","desc":""},{"name":"id","type":"number","desc":""},{"name":"name","type":"string","desc":""}],"behaviorTypes":[{"behaviorId":"Tween","name":"Tween"},{"behaviorId":"Pin","name":"Pin"}],"effectTypes":[],"members":["Sprite1"]}],"folders":[],"imageData":["data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAIJJREFUeF7t1wERACAMA7FNEbKRCUI+SOix5rp3zpvwWwH4AU5AB4Q7cJQgBShAAQpQIJwABjGIQQxiMIyAMYRBDGIQgxjEYDgBDGIQgxjEYBgBaxCDGMQgBjGIwXACGMQgBjGIwTAC1iAGMYhBDGIQg+EEMIhBDGIQg2EErEEM1hn8f5d1gUDQwQwAAAAASUVORK5CYII="]}
```

By the way, if you copy Family to new project and it works fine, then click on Family's name(e.g. 'Crash1'), it will also crash.

**Comment by AshleyScirra** [comment]
I finally figured out how to reproduce this - there's a missing step in the steps to reproduce. Pasting the family is successful. But showing the family properties is what crashes. To get this crash I have to click in the layout view to unselect the family, and then click back on the family in the project bar to show its properties.
