### ISSUE TITLE
r38 broke addon dev mode

### ISSUE THREAD

**Issue by TGeneDavis** [Scirra/Construct-3-bugs#514]
## Problem description

clicking "add dev addon..." button in r38 kills C3

## Attach a .c3p

Empty project with no new project yet clicked

## Steps to reproduce

1. Before loading a project or creating a new project, click "add dev addon"
2.See lots of red

## Observed result

Hard crash with lots of red on the screen

## Expected result

Anything but a total system collapse ; - )

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r38/main.js, line 2, col 203281
Message: Uncaught Error: missing dialog element with class name: okButton
Stack: Error: missing dialog element with class name: okButton at ǃT.ǃTp.ǃZS.ǃTV$.ǃXE (https://editor.construct.net/r38/main.js:2:311413) at ǃT.ǃTp.ǃZS.ǃTV$ (https://editor.construct.net/r38/main.js:2:339060) at Function.ǃT.ǃP (https://editor.construct.net/r38/main.js:2:203260) at Function.ǃVhf (https://editor.construct.net/r38/main.js:2:302933) at Function.ǃZG (https://editor.construct.net/r38/main.js:2:310473) at ǃT.ǃTp.ǃTI.ǃUgJ.ǃUkU (https://editor.construct.net/r38/main.js:149:12772) at HTMLButtonElement.ǃUkT.onclick (https://editor.construct.net/r38/main.js:149:8583)
Construct 3 version: r38
URL: https://editor.construct.net/
Date: Thu Jun 15 2017 06:46:04 GMT-0600 (MDT)
Uptime: 8 s

Unable to collect further diagnostic information because an exception was thrown while trying to collect it.

</details>

**Comment by TGeneDavis** [comment]
This happens when projects are loaded too, but it is easier to test if we don't cloud the issue with pesky code.

**Comment by TGeneDavis** [comment]
The problem isn't in r38.2
