### ISSUE TITLE
Crash every time when opening a project

### ISSUE THREAD

**Issue by ecations** [Scirra/Construct-3-bugs#5141]
I can send the c3p-file privately if needed? It started happening after trying to add a new sprite to an existing hierarchy in the editor. Here is the info:

Error report information
Type: unhandled exception
File: https://editor.construct.net/r268/components/editors/layoutView/layoutView.js, line 50, col 256
Message: Uncaught TypeError: Cannot read properties of null (reading 'fp')
Stack: TypeError: Cannot read properties of null (reading 'fp') at n6a (https://editor.construct.net/r268/components/editors/layoutView/layoutView.js:50:256) at p6a (https://editor.construct.net/r268/components/editors/layoutView/layoutView.js:50:48) at window.Zac.xM (https://editor.construct.net/r268/components/editors/layoutView/layoutView.js:178:114) at Array. (https://editor.construct.net/r268/components/editors/layoutView/layoutView.js:177:6) at window.Zk.dispatchEvent (https://editor.construct.net/r268/main.js:1041:32) at cRb (https://editor.construct.net/r268/components/editors/layoutView/layoutView.js:82:287)
Construct 3 version: r268
URL: https://editor.construct.net/
Date: Thu Oct 21 2021 15:44:11 GMT+0300 (Itä-Euroopan kesäaika)
Uptime: 21.3 s

Platform information
Browser: Chrome
Browser version: 94.0.4606.81
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
C3 release: r268 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.100.7107)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to investigate a report like this - please see the bug report guidelines.

If you really cannot reproduce the issue in a new project, all we can do is try to recover the project, but if the issue that caused it is not fixed, it could happen again. So I'd advise restoring a backup.

**Comment by ecations** [comment]
Hi!
I can't seem to replicate this from scratch, but I know exactly how to reproduce the crash in my working backup. All I need to do to get the crash back is to try to change the layer of one sprite. Maybe you can reproduce that with my file? I'll send it over.
