### ISSUE TITLE
R271 crashes when loading games with global layers

### ISSUE THREAD

**Issue by atlas-grey** [Scirra/Construct-3-bugs#5218]
## Problem description

Could not open my project in r271 without it crashing. I tried to recreate my project in r271 and experienced the crash again when I tried to create a global layer on a second layout (I have doors that open/close on layout transition). I have since recreated the problem again in the attached .c3p file.

## Attach a .c3p

https://www.dropbox.com/s/inaw1m4lxe5stkp/globallayer_off.c3p?dl=0

## Steps to reproduce

1. Select layer "Global" in layout 1
2. Under Layer Properties go to the Global drop down and select Yes
3. Select the Layout 2 tab

## Observed result

Instant crash

## Expected result

The Global layer should have reproduced itself in the second layout, as with previous versions of C3

## More details
Global layers worked successfully in r270, it's only with the r271 update I have experienced this problem

I have only tested this in the Chrome Browser.

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r271/main.js, line 482, col 182
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'pua')
Stack: TypeError: Cannot read properties of undefined (reading 'pua') at Object.CCG.xka (https://editor.construct.net/r271/main.js:482:182) at Object.CCG.Ik (https://editor.construct.net/r271/main.js:497:261) at d.yf (https://editor.construct.net/r271/projectResources.js:1171:482) at d.yf (https://editor.construct.net/r271/projectResources.js:1171:298) at d.yf (https://editor.construct.net/r271/projectResources.js:1132:460) at vTb (https://editor.construct.net/r271/components/editors/layoutView/layoutView.js:77:284)
Construct 3 version: r271
URL: https://editor.construct.net/r271/
Date: Wed Nov 10 2021 14:00:08 GMT+0800 (Australian Western Standard Time)
Uptime: 236.9 s

Platform information
Browser: Chrome
Browser version: 95.0.4638.69
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
C3 release: r271 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by atlas-grey** [comment]
Oops, just saw the issue has been addressed and a hotfix is on the way. Thanks
