### ISSUE TITLE
[delete this] didn't noticed that bug-report about INVERT in r273 is already exists

### ISSUE THREAD

**Issue by pl0y** [Scirra/Construct-3-bugs#5276]
## Problem description

If you invert "IS PINNED" condition, editor will crash with error

## Attach a .c3p

https://drive.google.com/file/d/14k6FXva2CVUVbWEwe8vYFJPE95Bnf8mI/view

## Steps to reproduce

1. create sprite or 3dshape with PIN behaviour
2. create "IS PINNED" condition
3. invert "IS PINNED" condition

## Observed result
the editor will crash with error

## Expected result
no crashes or errors

## More details

**Affected browsers/platforms:** 
Win7 Chrome 96.0 & Firefox 94.0

**First affected release:** 
worked in r272.2 but broke in r273
## System details

<details><summary>View details</summary>

PASTE HERE
Error report information
Type: unhandled exception
File: https://editor.construct.net/r273/components/editors/eventSheetView/eventSheetView.js, line 98, col 53
Message: Uncaught TypeError: H9a.oAc is not a constructor
Stack: TypeError: H9a.oAc is not a constructor at d.FHb (https://editor.construct.net/r273/components/editors/eventSheetView/eventSheetView.js:98:53) at https://editor.construct.net/r273/components/editors/eventSheetView/eventSheetView.js:93:458 at https://editor.construct.net/r273/main.js:1678:100
Construct 3 version: r273
URL: https://editor.construct.net/r273/
Date: Sun Nov 28 2021 23:50:28 GMT+0300 (GMT+03:00)
Uptime: 10.5 s

Platform information
Browser: Chrome
Browser version: 96.0.4664.45
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
C3 release: r273 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 750 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
</details>

**Comment by pl0y** [comment]
UPD: r273 crashes if you invert ANY condition
