### ISSUE TITLE
Crash with save and timelines

### ISSUE THREAD

**Issue by ecations** [Scirra/Construct-3-bugs#5356]
Hi!

I'm getting this crash when trying to use the save mechanism together with timelines:
[Construct 3] Loaded state from storage (165599 chars)
runtime.js:99 [Construct 3] Failed to load state from storage:  Error: cannot call while loading state - wait until afterload event
    at C3Runtime.GetInstanceByUID (runtime.js:91:1207)
    at Track.CanInstanceBeValid (trackState.js:6:66)
    at timelineState.js:32:32
    at Array.some (<anonymous>)
    at Timeline.HasValidGlobalTracks (timelineState.js:31:532)
    at Timeline._OnBeforeChangeLayout (timelineState.js:19:165)
    at TimelineManager._OnBeforeChangeLayout (timelineManager.js:20:380)
    at Array.TimelineManager._beforeLayoutChange (timelineManager.js:3:111)
    at EventHandler._FireNonCancellable (handler.js:7:27)
    at EventDispatcher.dispatchEvent (dispatcher.js:4:235)

runtime.js:86 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'Draw')
    at C3Runtime._Render (runtime.js:86:207)
    at C3Runtime.Render (runtime.js:85:144)
    at C3Runtime.Tick (runtime.js:72:399)

I don't want to send my project publicly, but I have sent a copy to Ashley through email.

Steps to reproduce:
-Preview the project
-Choose start by hitting x (or enter)
-Move the player outside from the house and then back inside (to create a save)
-Move the player outside again
-Press S to open menu
-Press arrows to go to settings gear icon and press x to open settings
-Choose "return to title screen" with x
-Now there should be a "continue" button in the title screen
-Choose continue with x
-The game will freeze and we get the console error above

Special note:
The crash doesn't seem to happen if I open settings and go to the title screen while I'm inside a house. Only outside in the world map. This further seems to indicate that the Timeline object might be the problem, since I only have timelines playing in the world map.

Operating system is Windows 10.
Tested with Chrome 96.0.4664.110 (Official Build) (64-bit) and Brave.
Construct is latest stable.

**Comment by DiegoScirra** [comment]
Can you share your project?

**Comment by DiegoScirra** [comment]
This should be fixed in the next beta.
