### ISSUE TITLE
Preview not working and crashing software

### ISSUE THREAD

**Issue by saltandpixel** [Scirra/Construct-3-bugs#5367]
## Problem description

Press preview button. Nothing happens. 3-5 seconds pass and Construct crashes.

## Attach a .c3p

[crashed.zip](https://github.com/Scirra/Construct-3-bugs/files/7856827/crashed.zip)

## Steps to reproduce

1. load game
2. press preview
3. wait for crash

## Observed result

Crash Report

## Expected result

Preview my game.

## More details

Browser: Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: error fetching exporters/_templates/index.html (524 ) @ Error: error fetching exporters/_templates/index.html (524 ) at uaa (https://editor.construct.net/r276-2/main.js:144:256) at async VNa (https://editor.construct.net/r276-2/projectResources.js:468:244) at async Promise.all (index 0) at async WNa (https://editor.construct.net/r276-2/projectResources.js:468:178) at async Promise.all (index 1) at async cOa (https://editor.construct.net/r276-2/projectResources.js:471:44)
Stack: Error: error fetching exporters/_templates/index.html (524 ) at uaa (https://editor.construct.net/r276-2/main.js:144:256) at async VNa (https://editor.construct.net/r276-2/projectResources.js:468:244) at async Promise.all (index 0) at async WNa (https://editor.construct.net/r276-2/projectResources.js:468:178) at async Promise.all (index 1) at async cOa (https://editor.construct.net/r276-2/projectResources.js:471:44)
Construct 3 version: r276.2
URL: https://editor.construct.net/
Date: Wed Jan 12 2022 13:22:07 GMT-0500 (Eastern Standard Time)
Uptime: 129.2 s

Platform information
Browser: Chrome
Browser version: 97.0.4692.71
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.100.7642)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by saltandpixel** [comment]
I don't know why, but it seems to have fixed itself.
