### ISSUE TITLE
ERROR IN ANDROID EXPORT IN R286 AND R287

### ISSUE THREAD

**Issue by Sirtaximan** [Scirra/Construct-3-bugs#5546]
## Problem description

 The export to android is broken in versions r286 and r287.

## Steps to reproduce

1. Open the project in C3 r287
2. Export it for android apk
3. Contemplate the problem

## Observed result

 An error occurs.

## Expected result

 C3 should create an .apk for android

## More details
 

**Affected browsers/platforms:**  Android

**First affected release:**  r286

## System details

<details><summary>View details</summary>

main.js:759 Error exporting:  Error: Invalid Android version
    at vvb (/r287/exporters/cordova/exporter.js:17:274)
    at hvb (/r287/exporters/cordova/exporter.js:16:362)
    at kvb (/r287/exporters/cordova/exporter.js:8:156)
    at async p6.KH.$Pa.aQ (/r287/exporters/cordova/exporter.js:29:388)
    at async I6a.nlc (/r287/projectResources.js:2884:238)
    at async Object.CCG.ipa (/r287/main.js:759:144)

</details>

**Comment by AshleyScirra** [comment]
Android builds work fine for me in r286. In r287 there's a regression that stops Android exports working. It should be fixed for the next beta. (Pinning and leaving open for visibility.)

**Comment by KENYONBcom** [comment]
Can't wait for the fix. This was driving me nuts!
