### ISSUE TITLE
Enabling Preview On Sin Behaviour Crashes C3

### ISSUE THREAD

**Issue by simonpaulkeating** [Scirra/Construct-3-bugs#5715]
## Problem description

C3 crashes when I enable the preview on a Sine behaviour. In my case the object with the Sine behaviour was a part of a hierarchy with both a child AND and parent. 

## Steps to reproduce

1. Go to Chr_Layout_1
2. Select the Valcano_Main instance
3. Add a Sine Behaviour
4. Click the preview checkbox in the sin behaviour

## Observed result

Construct 3 crashes

## Expected result

It shouldn't crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r295/projectResources.js, line 758, col 59
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'rD')
Stack: TypeError: Cannot read properties of undefined (reading 'rD') at d.mib (https://editor.construct.net/r295/projectResources.js:758:59) at d.Pb (https://editor.construct.net/r295/projectResources.js:757:71) at d.Pb (https://editor.construct.net/r295/projectResources.js:757:108) at d.RNb (https://editor.construct.net/r295/projectResources.js:748:193) at d.Rib (https://editor.construct.net/r295/projectResources.js:748:244) at d.Cn (https://editor.construct.net/r295/projectResources.js:749:230) at d.rmc (https://editor.construct.net/r295/projectResources.js:778:456) at d.Cf (https://editor.construct.net/r295/projectResources.js:1263:220) at d.Cf (https://editor.construct.net/r295/projectResources.js:1263:76) at d.Cf (https://editor.construct.net/r295/projectResources.js:1222:460)
Construct version: r295
URL: https://editor.construct.net/r295/
Date: Thu May 19 2022 08:41:32 GMT-0300 (Argentina Standard Time)
Uptime: 1477 s

Platform information
Product: Construct 3 r295 (beta)
Browser: Chrome 101.0.4951.67
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
[Bomb.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8728699/Bomb.c3p.zip)

</details>

**Comment by AshleyScirra** [comment]
The provided project uses a third-party addon (Plugin Scml (Spriter) by BrashMonkey). Please provide a project not using any third-party addons as per the bug report guidelines.

**Comment by simonpaulkeating** [comment]
Oops sorry, I'll create a new one now. Please stand by..

**Comment by simonpaulkeating** [comment]
New c3p with the basics has the same crash. See below.

[TestCrash1.zip](https://github.com/Scirra/Construct-3-bugs/files/8728944/TestCrash1.zip)

1. Select the 'hot pink' child instance.
2. Add a SIne behaviour
3. CHeck the preview
4. C3 will crash

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta. Was introduced in r295 along with the feature to transform timelines with hierarchies.

**Comment by simonpaulkeating** [comment]
Great. Thanks!
