### ISSUE TITLE
Key in text save window crashed

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#60]
## Problem description

This is a severe bug: Can't save file because it will crash when keying a save name for it.

## Steps to reproduce

1. Create new project.
2. Save project to local browser or cloud.
3. Type something in the save name textbox.

## Observed result

Crashed.

## Expected result

Don't crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r17/main.js, line 2, col 210681
Message: Uncaught TypeError: Cannot read property 'toLowerCase' of null
Stack: TypeError: Cannot read property 'toLowerCase' of null at Function.ǃE.ǃbTE (https://editor.construct.net/r17/main.js:2:210681) at ǃE.ǃv.ǃEgd.ǃJU (https://editor.construct.net/r17/main.js:50:40651) at window.addEventListener.te (https://editor.construct.net/r17/main.js:50:40118)
Construct 3 version: r17
URL: https://editor.construct.net/index.html
Date: Wed Apr 12 2017 13:01:18 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 84.1 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by jaydonteh** [comment]
close as duplicate: https://github.com/Scirra/Construct-3-bugs/issues/58
