### ISSUE TITLE
Undo after changing tiled background causes crash

### ISSUE THREAD

**Issue by raassh-23** [Scirra/Construct-3-bugs#6092]
## Problem description

When you change the image of an tiled background, then you undo the change, the editor will crash.

## Attach a .c3p

Just create a new project

## Steps to reproduce

1. Create a new project
2. Add a tiled background
3. Change the image of the tiled background
4. Undo the change

## Observed result

The editor crashes

## Expected result

The editor should not crash

## More details

**Affected browsers/platforms:** Chrome 105.0.5195.102

**First affected release:** R308

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: cannot change duration of non-animated image @ Error: cannot change duration of non-animated image at d.gaa (https://editor.construct.net/r308/projectResources.js:719:156) at OXa.s9b.lf (https://editor.construct.net/r308/projectResources.js:1820:164) at rM.JLb.lf (https://editor.construct.net/r308/projectResources.js:1770:405) at self.hp.lf (https://editor.construct.net/r308/projectResources.js:1770:405) at pM.Cjc.lf (https://editor.construct.net/r308/projectResources.js:1770:405) at pM.Cjc.lf (https://editor.construct.net/r308/projectResources.js:1862:207) at window.qc.Th (https://editor.construct.net/r308/projectResources.js:1774:19) at d.Th (https://editor.construct.net/r308/projectResources.js:1655:95) at window.Hab.Th (https://editor.construct.net/r308/main.js:2345:269) at Array. (https://editor.construct.net/r308/main.js:2318:478)
Stack: Error: cannot change duration of non-animated image at d.gaa (https://editor.construct.net/r308/projectResources.js:719:156) at OXa.s9b.lf (https://editor.construct.net/r308/projectResources.js:1820:164) at rM.JLb.lf (https://editor.construct.net/r308/projectResources.js:1770:405) at self.hp.lf (https://editor.construct.net/r308/projectResources.js:1770:405) at pM.Cjc.lf (https://editor.construct.net/r308/projectResources.js:1770:405) at pM.Cjc.lf (https://editor.construct.net/r308/projectResources.js:1862:207) at window.qc.Th (https://editor.construct.net/r308/projectResources.js:1774:19) at d.Th (https://editor.construct.net/r308/projectResources.js:1655:95) at window.Hab.Th (https://editor.construct.net/r308/main.js:2345:269) at Array. (https://editor.construct.net/r308/main.js:2318:478)
Construct version: r308
URL: https://editor.construct.net/
Date: Sat Sep 10 2022 14:56:08 GMT+0700 (Western Indonesia Time)
Uptime: 29.2 s

Platform information
Product: Construct 3 r308 (stable)
Browser: Chrome 105.0.5195.102
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by raassh-23** [comment]
Nevermind, i didn't realize it was already fixed in R309. Closing the issues.
