### ISSUE TITLE
Google play plugin does not perform the sign out action

### ISSUE THREAD

**Issue by XIMIKATIK** [Scirra/Construct-3-bugs#6139]
When trying to sign out, the plugin gives an error, the second problem is why can't I turn off automatic login to profiles after the first login, I can't implement an exit if the player no longer wants to use google play service.

domSide.js:31 Exception in 'googleplay' handler 'signout': TypeError: Cannot read properties of null (reading 'clear')
    at Uy (cb=gapi.loaded_0?le=scs:821:390)
    at vz (cb=gapi.loaded_0?le=scs:834:201)
    at Object.signOut (cb=gapi.loaded_0?le=scs:850:446)
    at GooglePlayHandler._SignOut (domSide.js:4:220)
    at domSide.js:1:288
    at RuntimeInterface._OnEventFromRuntime (domSide.js:31:348)
    at RuntimeInterface._OnMessageFromRuntime (domSide.js:30:98)
    at _messageChannelPort.onmessage (domSide.js:12:284)

2.Issue №2 The On loaded trigger also fails.

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.
