### ISSUE TITLE
Switchting layout crashes Construct

### ISSUE THREAD

**Issue by rogerty** [Scirra/Construct-3-bugs#6169]
_disclaimer: I know that this report will likely be closed because it does not follow the guidelines._

**Problem description**
When I open edit mode in Timeline and switch to another layout, Construct crashes.

**How to reproduce/sample project**
I have tried to reproduce this issue, but I cannot.
That means I do not know what is causing it.
However, in my own personal project, I can reproduce it every time by doing the following:

steps:
1. Turn on Animation Edit mode. (which has a simple animation with 1 sprite)
2. Click on another layout tab.

**Regression?**
This is the first time I am using timelines, so I cannot say if this happened in previous releases.
If you want, I can send you my own project.

**Error report information**
Type: unhandled exception
File: https://editor.construct.net/r313/components/editors/layoutView/layoutView.js, line 171, col 236
Message: Uncaught TypeError: Cannot read properties of null (reading 'cs')
Stack: TypeError: Cannot read properties of null (reading 'cs') at d.nJa (https://editor.construct.net/r313/components/editors/layoutView/layoutView.js:171:236) at d.huc (https://editor.construct.net/r313/components/editors/layoutView/layoutView.js:162:183) at d.XO (https://editor.construct.net/r313/components/editors/layoutView/layoutView.js:158:77) at Array. (https://editor.construct.net/r313/components/editors/layoutView/layoutView.js:153:9) at window.sl.dispatchEvent (https://editor.construct.net/r313/main.js:1099:42) at I1b (https://editor.construct.net/r313/components/editors/layoutView/layoutView.js:86:310)
Construct version: r313
URL: https://editor.construct.net/r313/
Date: Wed Oct 05 2022 17:57:53 GMT+0200 (Midden-Europese zomertijd)
Uptime: 3829.3 s

Platform information
Product: Construct 3 r313 (beta)
Browser: Chrome 106.0.5249.91
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon R7 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Platform information**
Product: Construct 3 r313 (beta)
Browser: Chrome 106.0.5249.91
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 804 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon R7 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by DiegoScirra** [comment]
@rogerty

Can you share the project where the crash happens, it doesn't reproduce from a blank project, so there must be something specific and not obvious about your project.

**Comment by rogerty** [comment]
Yes, what is your preferred way to receive the project?
Is it possible to share the project only to Scirra?

**Comment by DiegoScirra** [comment]
You can send it to diego@scirra.com

**Comment by DiegoScirra** [comment]
Closing, never got a project that reproduces the issue.
