### ISSUE TITLE
Crash in r314 when naming a timeline track folder anything with the character ":" in it

### ISSUE THREAD

**Issue by SimplyChark** [Scirra/Construct-3-bugs#6186]
If any track folder in a timeline folder has a name with ":" in it, it crashes c3 and makes it unable to save project. 

I am unable to add a c3p project as it crashes when reproduced and makes it unable to save the file

## Steps to reproduce

1. Create c3 project
2. Add a timeline
3. Add a track folder
4. Name it ":"
5. Crash occurs

## Observed result

Crash and inability to save file

## Expected result

Give error similar to the following: "Character: ":" is an illegal character" and not allow the name

**Affected browsers/platforms:** 

Mac os and Windows, Chrome and Safari

**First affected release:** 

It seems it was broken since timeline track folders were existant.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: invalid folder name ':' @ Error: invalid folder name ':' at d.Wa (https://editor.construct.net/r314/projectResources.js:550:514) at d.Wa (https://editor.construct.net/r314/projectResources.js:1023:469) at d.Nk (https://editor.construct.net/r314/projectResources.js:1023:307) at https://editor.construct.net/r314/components/bars/timelineBar/timelineBar.js:9:188
Stack: Error: invalid folder name ':' at d.Wa (https://editor.construct.net/r314/projectResources.js:550:514) at d.Wa (https://editor.construct.net/r314/projectResources.js:1023:469) at d.Nk (https://editor.construct.net/r314/projectResources.js:1023:307) at https://editor.construct.net/r314/components/bars/timelineBar/timelineBar.js:9:188
Construct version: r314
URL: https://editor.construct.net/r314/
Date: Thu Oct 13 2022 18:56:39 GMT+0300 (GMT+03:00)
Uptime: 221.9 s

Platform information
Product: Construct 3 r314 (beta)
Browser: Chrome 105.0.5195.125
Browser engine: Chromium
Context: browser
Operating system: macOS 12.5.1
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M2, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by SimplyChark** [comment]
It also crashes if the name is "", "*", """", "@" and many other symbols

**Comment by AshleyScirra** [comment]
@DiegoScirra - timeline folders need to use the same validation as other project folders. This was changed this release cycle to enforce that folder names are valid to store on disk.
