### ISSUE TITLE
Search - Bug - If -> Search -> Go To Result In Dictionary -> When Dictionary Is Opened And In Table-Like Form

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#6294]
If you go to a dictionary search result on the search interface box while the dictionary is already opened a hard crash occurs.

## Attach a .c3p

[Search_Debug_0.zip](https://github.com/Scirra/Construct-3-bugs/files/10109211/Search_Debug_0.zip)

## Steps to reproduce

The steps are listed in comment form in Event Sheet 1.

## Observed result

Hard Crash

## Expected result

Go to search result located in the dictionary

## More details

**Affected browsers/platforms:** 
Chrome

r19
**First affected release:** 
r319.2

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: e.KL is not a function @ TypeError: e.KL is not a function at window.Ocb.Wja (https://editor.construct.net/r319-2/components/bars/findResultsBar/findResultsBar.js:16:99)
Stack: TypeError: e.KL is not a function at window.Ocb.Wja (https://editor.construct.net/r319-2/components/bars/findResultsBar/findResultsBar.js:16:99)
Construct version: r319.2
URL: https://editor.construct.net/r319-2/
Date: Mon Nov 28 2022 19:31:30 GMT-0700 (Mountain Standard Time)
Uptime: 516 s

Platform information
Product: Construct 3 r319.2 (beta)
Browser: Chrome 107.0.5304.121
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by OneRepCloser** [comment]
> #6256 dublicate

Closing due to duplicate bug report
