### ISSUE TITLE
Game crash when attaching a joint to an object with disabled Physics

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#6376]
## Problem description

Game crashed (black screen on start) when I added a physics joint. Checked the console to find this error:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'GetPosition')
    at PhysicsInstance._UpdateBodyToMatchInstance (runtime.js:50:449)
    at PhysicsInstance._DoCreatePrismaticJoint (runtime.js:41:175)
    at PhysicsInstance._CreatePrismaticJoint (runtime.js:40:80)
    at PhysicsInstance.CreatePrismaticJoint (runtime.js:82:6)
    at Action._RunBehavior (action.js:27:457)
    at EventBlock._RunActions_Fast (eventBlock.js:26:97)
    at EventBlock._RunAndBlock (eventBlock.js:24:220)
    at EventBlock.Run (eventBlock.js:21:212)
    at EventSheet._ExecuteTrigger (eventSheet.js:19:154)
    at EventSheet._TriggerForClass (eventSheet.js:13:302)
```
The cause with that the target object has `Physics.Enabled=false`.

## Attach a .c3p
[Physics.zip](https://github.com/Scirra/Construct-3-bugs/files/10352992/Physics.zip)

## Steps to reproduce

1. Run

## Observed result

Black screen, and console error.

## Expected result

Game runs normally, but the joint is not created. A console warning with helpful info will be better than an ambiguous crash.

## More details
You can test the workaround by enabling the disabled action in the first event.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
