### ISSUE TITLE
Unhandled rejection layout crash :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6532]
## Problem description

Construct crashes.

## Attach a .c3p

save open project: [save_open_project.zip](https://github.com/WilsonPercival/WilsonPercival/files/10735528/save_open_project.zip)

## Steps to reproduce

1. Create a new project.
2. Create a sprite.
3. Cut out the instance.
4. Remove the object from the project.
5. Create a new layout.
6. Paste the instance on the new layout and press Ctrl + Z (this should be quick).

## Observed result

https://user-images.githubusercontent.com/91274932/218821567-416fd42e-eb6c-4d78-9e72-d2030df6fa38.mp4

## Expected result

Construct does not crash.

## More details

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'Sq') @ TypeError: Cannot read properties of null (reading 'Sq') at window.Il.Sq (https://editor.construct.net/r330/components/editors/layoutView/layoutView.js:121:258) at window.Il.Keb (https://editor.construct.net/r330/components/editors/layoutView/layoutView.js:127:149)
Stack: TypeError: Cannot read properties of null (reading 'Sq') at window.Il.Sq (https://editor.construct.net/r330/components/editors/layoutView/layoutView.js:121:258) at window.Il.Keb (https://editor.construct.net/r330/components/editors/layoutView/layoutView.js:127:149)
Construct version: r330
URL: https://editor.construct.net/r330/
Date: Tue Feb 14 2023 19:20:52 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 76 s

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r330b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 193 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Merged in to tracking issue #6531

**Comment by WilsonPercival** [comment]
@AshleyScirra It looks like it works well! Great job!

**Comment by WilsonPercival** [comment]
@AshleyScirra I can still reproduce it in `r331b`.

https://user-images.githubusercontent.com/91274932/220736255-7478c0e1-778a-4e5e-80d8-33a2b4fafbb2.mp4

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'I') @ TypeError: Cannot read properties of null (reading 'I') at window.Ll.I (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:101:190) at l$a (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:45:160) at window.Ll.Web (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:129:111) at N9a (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:36:452)
Stack: TypeError: Cannot read properties of null (reading 'I') at window.Ll.I (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:101:190) at l$a (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:45:160) at window.Ll.Web (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:129:111) at N9a (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:36:452)
Construct version: r331
URL: https://editor.construct.net/r331/
Date: Wed Feb 22 2023 21:16:32 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 72.4 s

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
