### ISSUE TITLE
`Cannot read properties of undefined` in R339

### ISSUE THREAD

**Issue by Laserwolve** [Scirra/Construct-3-bugs#6979]
The below image can't be imported into the Animations Editor.

## Attach a .c3p
Image in question:
![021](https://user-images.githubusercontent.com/87336074/234466939-6b0e844b-fb8e-4fe2-811d-35ee8346135c.png)

## Steps to reproduce

1. Open a new project in any current beta (R337, R338, or R339)
2. Create a sprite
3. Drag the above image into the main pane of the Animations Editor for that sprite

## Observed result
The following message is observed, with no errors in the console:
![image](https://user-images.githubusercontent.com/87336074/234467648-f6268fdf-514e-401c-8644-7c7a65d7768f.png)
If the image was in a `.zip` archive, and dragged into the Animations pane, the follow message appears, and no errors in the console:
![image](https://user-images.githubusercontent.com/87336074/234363935-eabbdcdd-3a3b-45f3-bf3e-3da9564ebc17.png)
When dragging and dropping the image in as a frame, nothing happens, and the following error is displayed in the console:
![image](https://user-images.githubusercontent.com/87336074/234468738-005286f9-743e-4601-bcb9-65191e8a004b.png)

## Expected result

Animations are imported; functions correctly in R336 stable

## More details
I've edited this issue multiple times as I've trimmed down exactly which image was causing this issue. The image can be drag and dropped onto a layout without issues.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r336 (stable)
Browser: Edge 112.0.1722.58
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.58
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 282 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Laserwolve** [comment]
Attempting to close the animations editor after importing the above image crashes Construct with the following error:

```
Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'blob') @ TypeError: Cannot read properties of undefined (reading 'blob') at d.l (https://editor.construct.net/r339/projectResources.js:138:107) at async Rc.RE.Nza (https://editor.construct.net/r339/main.js:1277:286)
Stack: TypeError: Cannot read properties of undefined (reading 'blob') at d.l (https://editor.construct.net/r339/projectResources.js:138:107) at async Rc.RE.Nza (https://editor.construct.net/r339/main.js:1277:286)
Construct version: r339
URL: https://editor.construct.net/r339/
Date: Tue Apr 25 2023 21:27:08 GMT-0700 (Pacific Daylight Time)
Uptime: 169.3 s

Platform information
Product: Construct 3 r339 (beta)
Browser: Edge 112.0.1722.58
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.58
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 600 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex
```
